jabardigitalservice/super-app-cms

nuxt.config.js
package-lock.json
package.json
plugins/jds-design-system.js

Setup JDS Design system library
title: Setup JDS Design system library
participants: @yoslie @marsellavaleria19 @doohanas @agunghide @maulanayuseph

setup: install jds design system library

---

components/Sidebar/index.vue

Changes
fixing scrollbar on sidebar content
Evidence
title: fixing scrollbar on sidebar content
participants: @marsellavaleria19 @yoslie @Ibwedagama @rizfirman @doohanas @agunghide @maulanayuseph 
screenshot: https://user-images.githubusercontent.com/44119106/199175767-69204b8e-e960-4e51-bd89-63110ee36703.png

feat: update scrollbar on sidebar content

---

components/KlaimRW/index.vue
constant/klaim-rw.js
pages/index.vue
utils/index.js

slicing layout page klaim rw
title: slicing layout page klaim rw
participants: @yoslie @marsellavaleria19 @naufalihsank @Ibwedagama @agunghide

feat: slicing layout page klaim rw

---

components/KlaimRW/AddressTable/index.vue
components/KlaimRW/DetailAddress/index.vue
components/KlaimRW/index.vue

slicing layout modal detail address rw
title: slicing layout modal detail address rw
participants: @yoslie @marsellavaleria19 @doohanas @Ibwedagama @agunghide

feat: slicing layout modal detail address

---

components/KlaimRW/DetailAddress/index.vue

update z-index modal detail address
title: update z-index modal detail address in klaim rw
participants: @yoslie @Ibwedagama @doohanas @marsellavaleria19

style: update z-index modal detail address

---

components/KlaimRW/KlaimRwDetail/DetailTableComponent/index.vue
components/KlaimRW/KlaimRwDetail/index.vue
components/Popup/LogoutConfirmation.vue
components/Sidebar/Footer.vue
layouts/Dashboard.vue
pages/detail/_id/index.vue

Slicing layout detail klaim RW page
title: Slicing layout untuk halaman detail klaim RW
participants: @marsellavaleria19 @Ibwedagama @yoslie @doohanas @maulanayuseph 
screenshot: https://user-images.githubusercontent.com/44119106/200218548-79af4924-754e-4952-9440-068d692b0bdf.png

feat : slicing layout detail klaim RW page

---

components/Base/Breadcrumb/index.vue
components/Base/Header/index.vue
components/KlaimRW/KlaimRwDetail/index.vue
components/Sidebar/Item.vue
pages/detail/_id/index.vue

- add header component
- change font family  'lato' to 'roboto' for title 
title: menambah komponen header pada layout detail klaim RW
participants: @marsellavaleria19 @Ibwedagama @rizfirman @agunghide @yoslie @doohanas 
screenshot: https://user-images.githubusercontent.com/44119106/201624222-caf7ca68-ae5e-4551-ac0d-cac735e44f64.png

feat : add header component in detail akun rw page

---

components/KlaimRW/TableAction/index.vue
components/KlaimRW/index.vue
constant/klaim-rw.js
nuxt.config.js
package-lock.json
package.json
plugins/axios.js
utils/index.js

- update service api list klaim rw
- add component popup table action
- add function formatDate using date-fns-tz
- add api axios plugin to use custom api key
title: update list klaim rw service
participants: @yoslie @Ibwedagama @marsellavaleria19 @doohanas

update: list klaim rw service

---

components/KlaimRW/Popup/Information.vue
components/KlaimRW/index.vue

- update function verify user rw in page klaim rw
- add conditional show message and icon in popup info klaim rw
- add watcher query for pagination and page changes
https://user-images.githubusercontent.com/65396086/202605158-e74f60a4-1426-4858-b2ce-786057168ce5.mov
title: update function verification user rw in page klaim rw
participants: @yoslie @marsellavaleria19 @agunghide @doohanas

update: verify user in page klaim rw

---

components/KlaimRW/AddressTable/index.vue
components/KlaimRW/DetailAddress/index.vue
components/KlaimRW/index.vue

replace dummy data in popup detail address in list klaim rw with api data
title: replace dummy data in popup detail address in list klaim rw with api data
participants: @yoslie @agunghide @doohanas @marsellavaleria19

update: detail address

---

components/KlaimRW/index.vue
constant/klaim-rw.js

udpate function sorting data table list klaim rw
title: udpate function sorting data table list klaim rw
participants: @yoslie @rizfirman @naufalihsank @agunghide @doohanas @Ibwedagama @marsellavaleria19

feat: udpate function sorting data table list klaim rw

---

components/KlaimRW/TableAction/index.vue
components/KlaimRW/index.vue

add conditional status in popup table action list klaim rw
title: add conditional status in popup table action list klaim rw
participants: @yoslie @marsellavaleria19 @doohanas

update: add conditional status in popup table action list klaim rw

---

components/KlaimRW/KlaimRwDetail/index.vue

- integration data detail klaim RW page.
- create function verify and reject detail klaim rw page.
-detail klaim rw page
-reject confirmation
https://user-images.githubusercontent.com/44119106/202989910-753a307a-4fe7-47ee-8727-a84a5cf1b481.mp4
-verify confirmation
https://user-images.githubusercontent.com/44119106/202989979-cd0830f9-22fb-4f63-a77d-21afda940be1.mp4
title: Itegrasi data detail klaim rw dan membuat fungsi verifikasi dan tolak klaim rw pada halaman detail klaim RW
participants: @marsellavaleria19 @maulanayuseph @yoslie @agunghide @doohanas 
screenshot: https://user-images.githubusercontent.com/44119106/203206992-c10a662f-c46c-423a-99bf-2103bb4f84e5.png

update : integration data detail / create function verify & reject klaim rw in detail klaim page

---

components/KlaimRW/ViewDocument/index.vue
components/KlaimRW/index.vue

Add document SK RW modal popup view in list data
title: Add document SK RW modal popup view in list data
participants: @yoslie @marsellavaleria19 @Ibwedagama @rizfirman

feat: add document SK RW modal popup view in list data

---

components/KlaimRW/KlaimRwDetail/index.vue

- add component view document
- change button condition will show if status account 'Menunggu Verifikasi'
add popup view document SK
title: add popup view document SK in detail klaim rw page
participants: @marsellavaleria19 @doohanas @agunghide @rizfirman @yoslie

feat : add popup view document in detail kalim rw page

---

components/KlaimRW/index.vue

- update sort type value from `0, 1` to `asc, desc`
- update default value sorting data
title: Update sort type value and sort default value
participants: @yoslie @doohanas @Ibwedagama @agunghide

update: change sort type value and sort default value

---

components/KlaimRW/DetailAddress/index.vue
components/KlaimRW/index.vue

https://user-images.githubusercontent.com/65396086/204704541-d5cdca68-8ff7-401e-9360-cfcde3fa9e27.mov
title: Create loading state on view detail address in list klaim RW
participants: @yoslie @Ibwedagama @marsellavaleria19 @doohanas @agunghide

update: create loading state on view detail address in list klaim RW

---

plugins/axios.js

- handle expired refresh token in plugin
title : handle expired refresh token in plugin
participants: @marsellavaleria19 @yoslie @doohanas

update: handle expired refresh token in plugin

---

plugins/axios.js

- chore: add x-timestamp on header request
- title: chore: add x-timestamp on header request
- project: Jabar Super Apps
- participants: @adzharamrullah @marsellavaleria19 @Ibwedagama

chore: add x-timestamp on header request

---

plugins/axios.js

- refactor config header in axios plugin
title: refactor config header in axios plugin
participants: @marsellavaleria19 @adzharamrullah @Ibwedagama @yoslie @doohanas

chore : refactor config header in axios plugin

---

plugins/axios.js

- chore: hot fix customHeader axios

chore: hot fix customHeader axios

---

components/KlaimRW/index.vue

fix bug on search data by reset query page into default (`1`)
title: bug fix search data in list klaim rw by reset query page
participants: @yoslie @doohanas @marsellavaleria19 @agunghide @rizfirman

fix: bug fix search data by reset query page

---

components/KlaimRW/index.vue
plugins/axios.js

fix bug on search data by reset query page into default (`1`)
title: Deploy Update Production - hotfix bug search data
participants: @yoslie @marsellavaleria19

Deploy Update Production - hotfix bug search data

---

components/KlaimRW/ViewDocument/index.vue
components/KlaimRW/index.vue
utils/index.js

- [update: improvement fix pdf document viewer for larger file not shown](https://github.com/jabardigitalservice/super-app-cms/commit/931a656c979ab8f9ed1387456c0cf4255c301266)

Up to production

---

.github/workflows/production.yaml
.github/workflows/staging.yaml
nuxt.config.js
package-lock.json
package.json
plugins/vue-gtag.js

-remove google analytics package 
-add the google analytics id variable to the workflow
title: remove google analytics package & add the google analytics id variable to the workflow
participants: @marsellavaleria19 @Ibwedagama @agunghide @yoslie

chore: remove google analytics package & add the google analytics id variable to the workflow

---

components/KlaimRW/KlaimRwDetail/index.vue

- add erorr for test error js newrelic
title: test error js newrelic

chore:add error js

---

nuxt.config.js

- change name env newrelic
title: change value env newrelic

chore: update name value env newrelic

---

components/KlaimRW/KlaimRwDetail/DetailTableComponent/index.vue
components/KlaimRW/KlaimRwDetail/index.vue
components/KlaimRW/Popup/EditStatus.vue
components/KlaimRW/TableAction/index.vue

- add pop up for edit status claim rw
- update status c;aom rw from reject status
[ezgif.com-crop.webm](https://user-images.githubusercontent.com/44119106/222174979-b9357366-3db7-4cc6-8ef6-e4aed2990c72.webm)
title: add pop up for edit status claim rw & update status claim rw from reject status 
participants: @marsellavaleria19  @rayfajars @Ibwedagama @doohanas @agunghide

feat : add pop up for edit status claim rw & update status claim rw from reject status 

---

components/KlaimRW/KlaimRwDetail/index.vue
components/KlaimRW/Popup/EditStatus.vue

- fix options in select form edit status popup
title: fixed options in select form edit status popup
participants: @marsellavaleria19 @maulanayuseph @Ibwedagama @agunghide @rayfajars @yoslie

fix : fixed options in select form edit status popup

---

components/Base/Dialog/index.vue
components/KlaimRW/EditDocument/index.vue
components/KlaimRW/ViewDocument/index.vue

- change flow validation file
- add eror alert validation vilew
[screen-capture (2).webm](https://user-images.githubusercontent.com/58242304/223639856-70b7bad8-8217-41bc-8403-b6ad3ebfc353.webm)
title: add validation edit sk

Feat: add validation edit sk

---

components/KlaimRW/Popup/EditStatus.vue

- add variable for change status
- validation account status
title: add variable for change status & validation account status in edit status popup
participants: @marsellavaleria19 @rizfirman @rayfajars @doohanas

refactor: add variable for change status & validation account status in edit status popup

---

docs/pull_request_template.md

- add pull request template
title: add pull request template
participants: @marsellavaleria19 @rayfajars

feat: add pull request template

---

components/KlaimRW/KlaimRwDetail/index.vue
components/KlaimRW/index.vue
components/Sidebar/index.vue
layouts/Dashboard.vue
pages/activities/index.vue
pages/configuration/index.vue
pages/data-user/index.vue
pages/detail/_id/index.vue
pages/index.vue
pages/management-release/index.vue
store/index.js

- add dynamic global baseheader with vuex store
- changes layoust dashboard
title: refactor style layouts
participants:  @rayfajars @marsellavaleria19

Refactor: base header layouts

---

components/Base/Popup/index.vue
components/Base/ViewImage/index.vue
components/MessageNotif/Detail/index.vue
components/MessageNotif/ViewImage/index.vue
components/MessageNotif/index.vue
mixins/message-notif.js
pages/message-notif/detail/_id/index.vue

https://sharing.clickup.com/3808590/t/h/860q3rumv/OU8ND69LJT8I6OF
- add component layout detail message notification
- add popup show image
- integration detail message notification
- add action delete & publish message notification
- update table action on list message notification page
- update style button on component base popup
https://user-images.githubusercontent.com/44119106/226517996-13dbadac-b84b-40e7-9a1c-d1d04d334258.mp4
title: add layout & integration detail message notif message page
participants:  @marsellavaleria19 @rayfajars @rizfirman @agunghide

feat : add layout & integration detail message notification message page

---

components/Base/DragAndDropFile/index.vue
components/Base/PopupDragAndDropFile/index.vue
components/KlaimRW/KlaimRwDetail/index.vue
components/TicketMuseum/Detail/index.vue
components/TicketMuseum/index.vue
layouts/Dashboard.vue
mixins/tiket-museum.js
pages/ticket-museum/detail/_invoice/index.vue
pages/ticket-museum/index.vue

https://app.clickup.com/t/860q98xyq
- changes component drag and drop file edit rw to global component drag and drop file
- add detail ticketing museum
- add verify and reject on detail
title: add detail ticketing museum
participants: @rayfajars @marsellavaleria19 @doohanas @yoslie @rizfirman @agunghide

Feat: detail ticketing museum

---

components/Base/Dialog/index.vue
components/Base/PopupDragAndDropFile/index.vue
components/TicketMuseum/index.vue
docs/pull_request_template.md
mixins/message-notif.js

- add defaulty props
- add title on template pull request
- change function methods file drag and drop
title: refactor table and props dialog
participants: @rayfajars @marsellavaleria19 @naufalihsank @agunghide

Refactor: style table and props dialogs

---

components/MessageNotif/Form/index.vue
components/MessageNotif/UploadDocument/index.vue
components/MessageNotif/index.vue
pages/message-notif/add/index.vue

https://sharing.clickup.com/3808590/t/h/860qc1fq9/6H0JR88LIRDIXJW
- fix sorting on list message notification page
- add limit for input text on form message notification
- change height upload image and text are on form message dialog
title:  fixed sorting & add limit for input text on message notification feature
participants: @marsellavaleria19 @Ibwedagama @rayfajars @doohanas

Fix : sorting & add limit for input text on message notification feature

---

components/Sidebar/Item.vue
components/Sidebar/index.vue
constant/menu.js
middleware/guardRoutes.js
plugins/get-roles.js

https://app.clickup.com/t/860q98y69
- add guard routes by roles
- add roles menu
title: integration roles keycloack admin
participants: @rayfajars @marsellavaleria19 @agunghide @doohanas @maulanayuseph @Ibwedagama

Feat: integration roles keycloack admin

---

.github/workflows/production.yaml
components/TicketMuseum/Detail/index.vue
components/TicketMuseum/index.vue
constant/tiket-museum.js
pages/ticket-museum/detail/_invoice/index.vue

- integration API list ticketing museum
- integration API detail ticketing museum
- integration API verify and reject ticketing museum order
title: integration API list and detail ticketing museum
participants: @rayfajars @marsellavaleria19 @rizfirman @agunghide

Feat: integration list and detail ticketing museum

---

constant/menu.js
middleware/guardRoutes.js

- refactor guard routes first logins by roles
title: redirect first login by roles
participants: @rayfajars @marsellavaleria19 @maulanayuseph @maruf12 @rizfirman @agunghide @yoslie @doohanas

refactor: redirect first login by roles

---

components/Base/Popup/index.vue
components/Base/PopupLoading/index.vue
components/Base/TableAction/index.vue
components/ManagementRelease/Detail/index.vue
components/ManagementRelease/Form/index.vue
components/ManagementRelease/index.vue
components/ManajemenRelease/index.vue
constant/manajemen-release.js
constant/menu.js
middleware/guardRoutes.js
mixins/manajemen-release.js
pages/management-release/create/index.vue
pages/management-release/detail/_id/index.vue
pages/management-release/edit/_id/index.vue
pages/management-release/index.vue
plugins/vee-validate.js

- slicing manajemen rilis (detail, list, edit , create) pagers
- create component form reusable on create and edit manajemen rilis
- add flow and dummy integration API
title: slicing and flow manajemen rilis
participants: @rayfajars @marsellavaleria19 @Ibwedagama @maulanayuseph

Feat: manajemen rilis

---

constant/menuList.js
middleware/guardRoutes.js

- https://app.clickup.com/t/860r8fcrn
- refactor fix route detail user rw
title: fix route detail user rw
participants: @rayfajars @marsellavaleria19 @maulanayuseph @agunghide @naufalihsank @yoslie @doohanas

fix: error route detail in roles admin

---

mixins/klaim-rw.js

- fix error reject account rw
title: fix error reject account rw
participants: @rayfajars @marsellavaleria19 @doohanas

fix: error popup reject account rw

---

components/TicketMuseum/index.vue

change name button bukti pembayaran
title: feat change name button bukti pembayaran
participants: @rayfajars @marsellavaleria19 @doohanas

feat: change name button bukti pembayaran

---

components/Aduan/AduanMasuk/Detail/index.vue

- change property object API
title: update property object API on page detail complaint
participants: @marsellavaleria19 @Ibwedagama @naufalihsank

refactor : update property object API on page detail complaint

---

constant/aduan-masuk.js
constant/menuList.js
pages/aduan/aduan-di-proses/index.vue
pages/aduan/aduan-masuk/index.vue
pages/aduan/dialihkan-ke-span/index.vue

- fix routes menu guard routes aduan
- fix url Klain akun rw
title: fix routes menu guard routes aduan
participants: @rayfajars @marsellavaleria19 @maulanayuseph @Ibwedagama @sheilaazhara @agunghide @yoslie

fix: routes menu guard routes aduan

---

constant/menuList.js

- fix link active page aduan
title: fix link active page aduan
participants:  @rayfajars @marsellavaleria19 @doohanas @sheilaazhara

fix: edit menu list

---

components/Aduan/DialogViewImage/index.vue
components/Dialog/InputTextArea/index.vue
mixins/popup-aduan-masuk.js

- [change variable for check input on dialog input text area](https://github.com/jabardigitalservice/super-app-cms/commit/6bce032c61e7a6a1aa22b77a149409348c507e95)
- [update height & function swiper](https://github.com/jabardigitalservice/super-app-cms/commit/b9b384d9696e36db34083eb2b879f579cda063b8)
- [change variable for show popup new image on mixin popup ad…](https://github.com/jabardigitalservice/super-app-cms/commit/0977c774396c913ab7661882802a4c36423fc99e)
title: change variable & function on dialog view image
participants: @marsellavaleria19 @Ibwedagama @rayfajars

Refactor: change variable & function on dialog view image

---

components/Aduan/TabBar/List/index.vue
components/Aduan/index.vue
components/Dialog/InputText/index.vue
constant/aduan-masuk.js
mixins/popup-aduan-masuk.js
pages/aduan/dialihkan-ke-span-lapor/index.vue

- using component complaint on page list complaint diverted to span
- slicing layout popup dialog input id span
- change header list complaint diverted to span on constant
- add column for show list complaint diverted to span
- change width select form on component complaint
title: change component complaint to page list complaint diverted to span
participants: @marsellavaleria19 @rizfirman @rayfajars @doohanas

feat : change component complaint to page list complaint diverted to span

---

components/Aduan/Detail/index.vue
components/Aduan/index.vue
constant/aduan-masuk.js
pages/aduan/aduan-masuk/detail/_id/index.vue
pages/aduan/aduan-masuk/index.vue

- add component & function button detail on page detail complaint
- change using component 'Aduan' on page list & detail complaint
- add object complaint button detail on constant file
title: change component on page list & detail complaint
participants: @marsellavaleria19 @rayfajars @doohanas

refactor : change component on page list & detail complaint

---

components/Aduan/Dialog/DetailStatusSpanLapor/CardSpanLapor/index.vue
components/Aduan/Dialog/DetailStatusSpanLapor/index.vue
mixins/popup-aduan-masuk.js
pages/aduan/dialihkan-ke-span-lapor/detail/_id/index.vue

- slicing layout popup tracking status span
- add button input id span on component detail complaint
- remove variable show popup image 
title: slicing popup tracking status span
participants: @marsellavaleria19 @Ibwedagama @agunghide @rayfajars @yoslie @doohanas

feat : slicing popup tracking status span

---

components/Aduan/Detail/index.vue
components/Aduan/index.vue
components/Base/Dialog/Footer/index.vue
components/Dialog/InputText/index.vue
mixins/popup-aduan-masuk.js

- add function for integration popup input id span
- add complaint status for showing button & menu action on feature complaint diverted to span
- remove params data dialog on component base dialog footer
- change value emit on component dialog input text
title: integration popup input id span
participants: @marsellavaleria19 @Ibwedagama @rayfajars @doohanas

refactor : integration popup input id span

---

components/Aduan/Detail/index.vue
components/Aduan/index.vue
components/Base/Dialog/Footer/index.vue
components/Dialog/Confirmation/index.vue
components/Dialog/InputText/index.vue
components/Dialog/InputTextArea/index.vue
constant/aduan-masuk.js
mixins/popup-aduan-masuk.js
pages/aduan/aduan-masuk/detail/_id/index.vue

- add function for show & submit popup confirmation & failed complaint
- change function for submit popup confirmation & failed on feature complaint
- remove value status on emit submit popup dialog confirmation
- remove value status & change label,placeholder on dialog input text area
- change verified & failed button detail on constant & page detail complaint
title: integration popup feature complaint
participants: @marsellavaleria19 @Ibwedagama @rizfirman @rayfajars @doohanas

refactor:integration popup feature complaint

---

components/Base/Dialog/index.vue

- hot fix trigger deploy production with prettier tailwind css
title: hotix triger deployment

hotfix: triget changes for deployment

---

components/Aduan/index.vue

-  add payload sort by updated at, sort type  desc & is admin on component complaint
title: add payload sort by updated at, sort type  desc & is admin on component complaint
participants: @marsellavaleria19  @rayfajars  @yoslie

refactor : add payload sort by updated at, sort type  desc & is admin on component complaint

---

constant/menuList.js
middleware/guardRoutes.js
nuxt.config.js

https://app.clickup.com/t/860rv0n8b
- refactor guard routes
- refactor path menu
title: Refactor middleware route
participants: @rayfajars @marsellavaleria19 @agunghide

Refactor: remove middleware route

---

components/Tahura/LaporanPendapatan/index.vue

- Fix height table
Before
After
title: Fix Height Table Tahura Laporan Pendapatan
participants: @MNAlfiansyah @ristianaditya @rayfajars @marsellavaleria19 @doohanas

fix: table height to big

---

pages/tahura/preview-pdf/_assurance-category-startDate-endDate-status-token.vue

- refactor changes token to params
title: refactor change get token from params
participants: @rayfajars @marsellavaleria19 @sheilaazhara

refactor: change get token from params

---

pages/tahura/preview-pdf/_assurance-category-startDate-endDate-status-token.vue

- remove component auth
- changes flow condition loader
title: change condition loader

refactor: change condition loader

---

.vscode/settings.json

- back settings. vscode json to default
title: back to default settings.json
participants: @rayfajars @marsellavaleria19 @Ibwedagama

fix: back to default settings.json

---

.vscode/settings.json

- active fixAll on vscode settings
title: active fixAll and add prettier for vue on vscode settings
participants: @rayfajars @marsellavaleria19 @doohanas @agunghide

feat: active fixAll and add prettier for vue on vscode settings

---

pages/tahura/preview-pdf/_assurance-category-startDate-endDate-status-token.vue

- add token on fetching generate pdf
title: add token routes params in fetchin generate pdf
participants: @rayfajars @marsellavaleria19 @agunghide @sheilaazhara

feat: add token routes params in fetchin generate pdf

---

components/Dialog/InputText/index.vue
mixins/popup-aduan-masuk.js
plugins/vee-validate.js

- change rules of vee validate 
Wrong Input
Correct Input
title: validation for input sp4n
participants: @rayfajars @marsellavaleria19 @ristianaditya @MNAlfiansyah

refactor: validation for input sp4n

---

components/Dialog/InputText/index.vue

- refactor reusable  condition rules in base dialog input text 
title: remove conditon in rules input text
participants: @rayfajars @marsellavaleria19 @yoslie @doohanas

refactor: remove conditon in rules input text

---

pages/tahura/preview-pdf/_assurance-category-startDate-endDate-status-token.vue

- change object name in post generate pdf
title: change object name in post generate pdf
participants: @rayfajars @marsellavaleria19 @doohanas

refactor: change object name in post generate pdf

---

components/Aduan/Detail/index.vue
components/Aduan/index.vue
pages/aduan/aduan-dari-span-lapor/detail/_id/index.vue

https://app.clickup.com/t/860rqta50
- [add component dialog add complaint & show data complaint on component complaint](https://github.com/jabardigitalservice/super-app-cms/commit/d306435ee286aec02a1829d754ee7882a3231f62)
- [change width on component complaint detail](https://github.com/jabardigitalservice/super-app-cms/commit/8d2720bf730d980027b15ec6ceb4b1739ba9ed3a)
- [add page detail complaint from span](https://github.com/jabardigitalservice/super-app-cms/commit/b923721dbbf46fe837f7f72e2f8da84bdae43e2f)
title: add page detail complaint from span
participants: @marsellavaleria19 @doohanas @rayfajars

feat : add page detail complaint from span

---

components/Tahura/LaporanPendapatan/index.vue
pages/tahura/preview-pdf/_assurance-category-startDate-endDate-status-token.vue
utils/index.js

https://app.clickup.com/t/860rpk7aq
- add export excel and formated date in excel
- proses response generate pdf 
EXPORT PDF : 
EXPORT EXCEL :
title: Fix download generate pdf and format date generate excel
participants: @rayfajars @marsellavaleria19 @Ibwedagama @doohanas

Fix: download generate pdf and format date generate excel

---

components/Tahura/DaftarPesanan/index.vue
components/Tahura/LaporanPendapatan/index.vue
components/Tahura/TabBar/index.vue
constant/tahura.js
pages/tahura/daftar-pesanan/detail/_invoice/index.vue

https://app.clickup.com/t/860rpk7bk
- integration API count order
- integration list order daftar pesanan
- add pages detail pesanan
title: integration api list and count daftar pesanan tahura
participants: @rayfajars @marsellavaleria19 @yoslie @Ibwedagama @agunghide

Feat: integration api list and count daftar pesanan tahura

---

components/Aduan/Dialog/AddComplaint/Form/InformationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/LocationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/AddComplaint/index.vue
components/Base/TextArea/index.vue
components/Dialog/WithStepper/index.vue
package-lock.json

https://app.clickup.com/t/860rqu336
- add condition disabled chained select
- add condition button kembali on first form
- add flow other form complaint
[screen-capture (1).webm](https://github.com/jabardigitalservice/super-app-cms/assets/58242304/42daff27-b473-46d2-9572-130b29e3cba4)
title: add sub kategori and condition buttom kembali on tambah aduan

Feat : add sub kategori and condition buttom kembali on tambah aduan

---

components/Tahura/LaporanPendapatan/index.vue

- remove function export pdf on laporan pendapatan tahura
title: remove export pdf on tahura laporan pendapatan
participants: @rayfajars @marsellavaleria19 @agunghide

refactor: remove export pdf on tahura laporan pendapatan

---

constant/menuList.js

- add roles tahura_officer on menu tahura 
title: add roles tahura officer
participants: @rayfajars @marsellavaleria19 @yoslie @agunghide

feat: add roles tahura officer

---

constant/menuList.js

add roles mraj officer
title: add roles mraj officer

feat: add roles mraj officer

---

constant/menuList.js

add roles super admin
title: add roles super admin

feat: add roles super admin

---

middleware/guardRoutes.js

- chore add midleware roles
title: add condition roles first login tahura

chore: add condition roles first login tahura

---

components/MessageNotif/Detail/index.vue
components/MessageNotif/Form/index.vue
components/MessageNotif/index.vue
constant/menuList.js
constant/message-notif.js

- refactor comment platform and topik on list, detail and form on menu pesan
- hide / comment menu aduan
title: pesan comment form platform and topic
participants: @rayfajars @marsellavaleria19 @sheilaazhara

Refactor: pesan comment form platform and topic

---

constant/menuList.js

remove comment menu list complaint
title: remove comment menu list complaint
participants:  @marsellavaleria19 @rizfirman @doohanas

refactor : remove comment menu list complaint

---

components/Aduan/index.vue

- fixing sorting by created at on component complaint
- [remove filter list statistic complaint on component complaint
title: fix sorted by created date not working & added tab bar status verification on page list determining authority
participants:  @marsellavaleria19 @rayfajars @Ibwedagama @yoslie

fix : sorted by created date not working & added tab bar status verification on page list determining authority

---

components/Aduan/index.vue

fix sorting by created date on component complaint
title:  fix sorting by created date on page list determining authority
participants:  @marsellavaleria19 @rayfajars

fix : sorting by created date on page list determining authority

---

components/Aduan/Detail/index.vue

add function for show category & sub category on component complaint detail
title: refactor add function for show category & sub category on page detail complaint from span
participants:  @marsellavaleria19 @Ibwedagama @rizfirman @rayfajars @yoslie

refactor : add function for show category & sub category on page detail complaint from span

---

components/Tahura/DaftarPesanan/index.vue

- add condition seven day later date range
title: refactor add condition date range seven days
participants: @rayfajars @marsellavaleria19 @sheilaazhara @rizfirman @doohanas

refactor: add condition date range seven days

---

components/Aduan/DaftarIKP/Table/index.vue
constant/daftar-ikp.js
pages/aduan/penginputan-ikp/index.vue

https://app.clickup.com/t/9003239225/CES-452
- add page daftar IKP
title: add component daftar IKP
participants: @rayfajars @marsellavaleria19 @yoslie

feat: add component daftar IKP

---

components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Aduan/TabBar/Detail/index.vue
components/Base/Detail/MenuButton/index.vue
constant/aduan-masuk.js
mixins/popup-aduan-masuk.js
pages/aduan/penginputan-ikp/detail/_id/index.vue

https://app.clickup.com/t/9003239225/CES-458
- slicing layout & integration page detail input ikp
- change for show tab by complaint status 
- change condition show data table on component complaint detail
title:
participants:  @marsellavaleria19 @rayfajars @doohanas

feat : slicing layout & integration page detail input ikp

---

components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/index.vue

- add status color on component complaint
- change status color on component complaint detail
title: add some status color on feature input ikp
participants:  @marsellavaleria19 @Ibwedagama @rizfirman @agunghide @rayfajars @doohanas

refactor : add some status color on feature input ikp

---

components/Aduan/Dialog/AddComplaint/index.vue

-  add reset state isError after close information form add complaint
title: refactor add reset state isError after close information form add co
participants: @rayfajars @marsellavaleria19 @yoslie @doohanas

refactor: add reset state isError after close information form add complaint

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/DaftarIKP/index.vue
components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Dialog/ViewDocument/ListDocument/index.vue
components/Aduan/Dialog/ViewDocument/ListImage/index.vue
components/Aduan/DialogViewImage/index.vue
constant/daftar-ikp.js
package-lock.json
package.json

https://app.clickup.com/t/9003239225/CES-3306
- add function download file dokumen bukti
[screen-capture (5).webm](https://github.com/jabardigitalservice/super-app-cms/assets/58242304/ae0edd4e-e2e9-44c4-9ff8-d7ae0ffc9329)
title: Feat dokumen bukti aduan
participants: @rayfajars @marsellavaleria19 @doohanas

Feat: dokumen bukti aduan

---

assets/css/style.css
components/Aduan/Dialog/CreateIkp/CardIkpNarrative/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/IkpNarrative/index.vue
package-lock.json
package.json
tailwind.config.js

- setup tailwind line clamp
- add line clamp & popup ikp narrrative on component card ikp
- add function for show title ikp narrative on component dialog ikp narrative
title: add line clamp on ikp narrative & change icon field date on form create ikp
participants: @marsellavaleria19 @agunghide @rizfirman @Ibwedagama

Refactor : add line clamp on ikp narrative & change icon field date on form create ikp

---

.vscode/settings.json
components/Aduan/DaftarIKP/index.vue
components/Aduan/index.vue

pairing statistik api IKP
title: pairing statistic ikp
participants: @rayfajars @yoslie @agunghide @Ibwedagama @doohanas

Feat: pairing statistic ikp and aduan

---

components/Aduan/Dialog/FollowupComplaint/Pagination/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/IkpNarrative/index.vue
components/Base/Dialog/Footer/index.vue

- add pagination on list table ikp
- custom scroll & change background button when disabled
-  change type props showpopup on popup ikp narrative
- remove header daftar aduan ikp
title: add pagination & change background button when disabled on dialog followup complaint
participants: @marsellavaleria19 @rayfajars @doohanas @agunghide @sheilaazhara

refactor : add pagination & change background button when disabled on dialog followup complaint

---

components/Aduan/Detail/index.vue
components/Aduan/index.vue
utils/index.js

https://app.clickup.com/t/9003239225/CES-2894
- pairing statistic aduan
- add back query from detail to list
[screen-capture (6).webm](https://github.com/jabardigitalservice/super-app-cms/assets/58242304/6e6e26ce-c13b-459d-85c8-f44cb4e3b9e4)
title: Refactor list aduan warga for pairing statistic aduan
participants: @rayfajars @marsellavaleria19 @sheilaazhara @doohanas

Refactor: list aduan warga for pairing statistic aduan

---

components/Aduan/Dialog/CreateIkp/CardIkpNarrative/index.vue
components/Aduan/Dialog/CreateIkp/Dialog/EditNarrative/index.vue

- change limit character on edit ikp narrative
- change condition show ikp narrative on form create ikp
title: refactor change limit character on edit ikp narrative & condition show button ikp narrative
participants: @marsellavaleria19 @sheilaazhara @agunghide @rayfajars

refactor : change limit character on edit ikp narrative & condition show button ikp narrative

---

components/Aduan/DaftarIKP/index.vue
components/Aduan/index.vue
components/KlaimRW/index.vue
components/ManagementRelease/Detail/index.vue
components/ManagementRelease/Form/index.vue
components/ManagementRelease/index.vue
components/MessageNotif/Detail/index.vue
components/MessageNotif/index.vue
components/Tahura/DaftarPesanan/Detail/index.vue
components/Tahura/DaftarPesanan/index.vue
components/TicketMuseum/Detail/index.vue
components/TicketMuseum/index.vue

refactor add back query for list page on :
- klaim aku rw
- management release
- pesan
- tahura
- ticket museum
title: refactor add back query for list page
participants: @rayfajars @marsellavaleria19 @Ibwedagama

refactor: add back query for list page

---

components/Aduan/Detail/Table/Complaint/index.vue

- add data ikp deadline on detail complaint
title: refactor add data ikp deadline on detail complaint
participants: @marsellavaleria19 @agunghide @yoslie @Ibwedagama @rayfajars

refactor :  add data ikp deadline on detail complaint

---

components/Aduan/TabBar/List/index.vue
components/Aduan/index.vue
components/Tahura/DaftarPesanan/index.vue
components/Tahura/TabBar/List/index.vue

- pairing tabs aduan
- pairing tabs tahura
title: Feat pair tab statistic from query
participants: @rayfajars @marsellavaleria19 @Ibwedagama

Feat: pair tab statistic from query

---

components/Aduan/Dialog/CreateIkp/index.vue

- add function submit popup error information on form create ikp
title:  add function submit popup error information on form create ikp
participants: @marsellavaleria19 @rayfajars @doohanas @agunghide @yoslie

refactor : add function submit popup error information on form create ikp

---

components/Aduan/Dialog/CreateIkp/CardIkpNarrative/index.vue
components/Aduan/Dialog/CreateIkp/Dialog/EditNarrative/index.vue
components/Aduan/Dialog/IkpNarrative/index.vue
store/edit-ikp-narrative.js

- fixing show ikp narrative without space
- add limit on popup edit ikp narrative
- fixing function button submit & close on popup edit ikp narrative
title: fixing break words ,limit & function save and cancel on popup edit ikp narrative
participants: @marsellavaleria19 @rayfajars @Ibwedagama

fix : fixing break words,limit & function save and cancel on popup edit ikp narrative

---

components/Aduan/Detail/index.vue
components/Aduan/Dialog/FollowupComplaint/ListFollowupProcess/index.vue
components/Aduan/Dialog/ViewDocument/ListImage/index.vue
components/Aduan/DialogViewImage/index.vue
components/Aduan/TabBar/List/index.vue
components/Base/Breadcrumb/index.vue
components/Base/ButtonDropdown/index.vue
components/Base/Header/index.vue
components/Base/PopupSelect/index.vue
components/Base/TabList/index.vue
components/Base/TableAction/index.vue
components/TabBar/Menu/index.vue
components/Tahura/TabBar/Detail/index.vue
components/Tahura/TabBar/List/index.vue

change default props type array on some component
title: change default props type array on some component
participants: @marsellavaleria19 @rayfajars @azhargraha

refactor: change default props type array on some component

---

components/Aduan/Dialog/AddComplaint/index.vue
components/Base/Popup/index.vue
components/KlaimRW/Popup/EditStatus.vue
components/ManagementRelease/index.vue
components/MessageNotif/index.vue
components/Sidebar/Item.vue
components/TicketMuseum/index.vue

change computed naming using nouns on some component
title: refactor change computed naming using nouns on some component
participants: @marsellavaleria19 @Ibwedagama @doohanas @sheilaazhara

refactor: change computed naming using nouns on some component

---

components/Aduan/DaftarIKP/index.vue
components/Aduan/index.vue
components/Base/TabListString/index.vue
components/TabBar/Menu/index.vue
pages/aduan/penginputan-ikp/detail-ikp/_id/index.vue
pages/aduan/penginputan-ikp/index.vue

- refactor tab bar menu penginputan ikp
- add tab menu for list title
[screen-capture.webm](https://github.com/jabardigitalservice/super-app-cms/assets/58242304/fa921cf2-d7aa-4c71-9313-fcbe2fcc1cad)
title: Refactor tab bar menu
participants: @rayfajars @marsellavaleria19 @azhargraha @doohanas

Refactor: tab bar menu

---

components/Aduan/Detail/index.vue

-fixing show dialog followup complaint
title: fixing show dialog followup complaint
participants:  @marsellavaleria19 @Ibwedagama @azhargraha @yoslie

fix : fixing show dialog followup complaint

---

components/Aduan/DaftarIKP/index.vue
pages/aduan/penginputan-ikp/index.vue

- add props ikp type page on page list input ikp
title: add props ikp type page on page list input ikp
participants: @marsellavaleria19 @azhargraha @rayfajars

refactor : add props ikp type page on page list input ikp

---

assets/css/style.css
components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/DaftarIKP/index.vue
pages/aduan/instruksi-aduan-warga/detail/_id/index.vue
pages/aduan/instruksi-aduan-warga/index.vue

[CES-470 Membuat tampilan detail Instruksi Aduan Warga](https://app.clickup.com/t/9003239225/CES-470)
- add page detail instruction complaint of citizen
- add props detail page on page list instruction complaint of citizen
- change some filed on page detail instruction complaint of citizen
- add layout content for scrollbar on file style css
title: add detail page instruction complaint of citizen
participants: @marsellavaleria19 @Ibwedagama @rizfirman @yoslie @azhargraha

feat : add detail page instruction complaint of citizen

---

components/Sribaduga/DaftarPesanan/Detail/index.vue
components/Sribaduga/DaftarPesanan/index.vue
components/Sribaduga/TabBar/Detail/index.vue
components/Tahura/DaftarPesanan/Detail/index.vue
components/Tahura/LaporanPendapatan/index.vue
constant/menuList.js
constant/sribaduga.js
pages/sribaduga/daftar-pesanan/detail/_invoice/index.vue

[integrasi detail daftar pesanan](https://app.clickup.com/t/9003239225/CES-6131)
- create detail pesanan sribaduga page
title: create detail pesanan sribaduga page
participants: @rizfirman @marsellavaleria19 @rayfajars

create detail pesanan sribaduga page

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/Detail/index.vue
constant/aduan-masuk.js
pages/aduan/instruksi-aduan-warga/detail-aduan/_id/index.vue

[CES-6088 Menampilkan detail aduan warga](https://app.clickup.com/t/9003239225/CES-6088)
[style code & add type aduan instuksi aduan warga]
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/19934d76-3075-4103-91a3-0ada204b1a21
title:  add page detail complaint on instruction complaint of citizen
participants: @marsellavaleria19 @doohanas @azhargraha @agunghide @sheilaazhara @rizfirman @yoslie

Feat : add page detail complaint on instruction complaint of citizen

---

components/Aduan/Detail/index.vue
components/Base/Breadcrumb/index.vue
pages/aduan/instruksi-aduan-warga/detail-aduan/_id/index.vue
pages/aduan/instruksi-aduan-warga/detail/_id/index.vue
pages/aduan/penginputan-ikp/detail-ikp/_id/index.vue
pages/aduan/penginputan-ikp/detail/_id/index.vue
pages/aduan/penginputan-ikp/index.vue

- change condition show tab ikp on component detail complaint
- change style code & add props detail page
- change style code & add condition show navigation 'Detail Instruksi'
-  add disabled on detail page feature penginputan ikp & instruction complaint on citizen
- style code & add props detail complaint link in page detail
- add condition disabled on component base breadcrumb
title: add link page on page detail feature penginputan ikp & disabled breadcrumb on some page
participants: @marsellavaleria19 @sheilaazhara @rayfajars @azhargraha

Refactor : add link page on page detail feature penginputan ikp & disabled breadcrumb on some page

---

constant/daftar-ikp.js

refactor: style code & remove attribute sortable on object status header list ikp
title: remove attribute sortable on object status header list ikp
participants: @marsellavaleria19 @rayfajars @Ibwedagama @rizfirman

refactor: remove attribute sortable on object status header list ikp

---

.eslintrc.js
components/Sribaduga/LaporanPendapatan/index.vue
constant/menuList.js
constant/sribaduga.js
pages/sribaduga/laporan-pendapatan/index.vue
tailwind.config.js

- [CMS Sribaduga - Mengembangkan Fitur Laporan Pendapatan](https://app.clickup.com/t/9003239225/CES-5546)
- create laporan pendapatan sribaduga feature
title: create laporan pendapatan sribaduga feature
participants: @rizfirman @marsellavaleria19 @doohanas

create laporan pendapatan sribaduga feature

---

components/Base/ButtonDropdown/index.vue
components/Sribaduga/DaftarPesanan/Detail/index.vue
components/Sribaduga/DaftarPesanan/index.vue
components/Sribaduga/LaporanPendapatan/index.vue

- [CMS Sribaduga - Mengembangkan Fitur Laporan Pendapatan](https://app.clickup.com/t/9003239225/CES-5546)
- [CMS Sribaduga - Mengembangkan Fitur Daftar Pesanan (List Pesanan) ](https://app.clickup.com/t/9003239225/CES-5539)
- add download excel functionality
- show instance name in daftar pesanan
title: add download excel functionality & show instance name in daftar pesanan
participants: @rizfirman @Ibwedagama @marsellavaleria19 @agunghide

Feat/ticketing sribaduga/download excel

---

assets/css/style.css
components/Aduan/AccountManagement/index.vue
components/Aduan/Dialog/Account/index.vue
components/Base/Dialog/FooterNew/index.vue
components/Dialog/ConfirmationNew/index.vue
components/Dialog/InformationNew/index.vue
plugins/vee-validate.js

[CES-484 membuat tampilan tambah admin pada management akun admin](https://app.clickup.com/t/9003239225/CES-484)
- slicing layout dialog form add account
- add function & component to show form account
- add slot in footer dialog confirmation
- add custom validation for email
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/0ccd1309-b46f-43e1-b137-f4b0a66253bc
title: slicing layout form add account
participants: @marsellavaleria19 @doohanas @rayfajars @rizfirman

Feat : slicing layout form add account

---

components/Aduan/AccountManagement/Detail/TableDetail/index.vue
components/Aduan/AccountManagement/Detail/index.vue
components/Aduan/AccountManagement/index.vue
pages/aduan/management-akun/detail/_id/index.vue
store/management-account.js

[CES-7291 membuat tampilan detail management akun admin aduan sesuai status](https://app.clickup.com/t/9003239225/CES-7291l)
- add function to page detail management account
- add component & page detail management account complaint
- add store for management account
- page detail management account for unverified status
- page detail management account for not active status
- page detail management account for active status
title: slicing layout page detail management account complaint
participants:  @marsellavaleria19 @rayfajars @rizfirman @azhargraha

feat : slicing layout page detail management account complaint

---

components/Aduan/AccountManagement/Detail/TableDetail/index.vue
components/Aduan/AccountManagement/index.vue
components/Aduan/Dialog/Account/index.vue
components/Dialog/InformationNew/index.vue
constant/management-user.js
store/management-account.js
store/modals.js

[CES-7281 Menambahkan pengiriman ulang email verifikasi](https://app.clickup.com/t/9003239225/CES-7281)
- add function for show form resend email on page list & detail management account
- change payload name & add data for resend email
- change key for role & organization name for management account
- add payload on state & mutation store management account
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/19880544-8187-4b78-b878-50fd5048f1c6
title: slicing layout form resend email
participants:  @marsellavaleria19 @rizfirman @agunghide @rayfajars @yoslie

Feat : slicing layout form resend email

---

components/Aduan/AccountManagement/index.vue
components/Aduan/Dialog/Account/index.vue

- change integration get data role & organization using axios on page list management account
- change integration get data role & organization using axios on form add account & resend email
title: change integration get data role & organization using axios on feature management account complaint 
participants: @marsellavaleria19 @Ibwedagama @agunghide @azhargraha @rayfajars @doohanas

refactor : change integration get data role & organization using axios on feature management account complaint 

---

components/Aduan/AccountManagement/Detail/TableDetail/index.vue

- add condition when nip field show
- change position field email, nip & employee status
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/6800e47c-c6c2-4957-b9a5-d3feeec9df6b
title: change position some field & add condition show NIP field on page detail management account complaint
participants: @marsellavaleria19 @azhargraha @yoslie @doohanas

Refactor : change position some field & add condition show NIP field on page detail management account complaint

---

components/Aduan/AccountManagement/Detail/TableDetail/index.vue
components/Aduan/AccountManagement/Detail/index.vue
components/Aduan/AccountManagement/index.vue

- integration list data management account complaint with axios on page list management account complaint
- Integration data detail management account with axios on page detail management account complaint
title: integration data management account complaint with axios
participants: @marsellavaleria19 @Ibwedagama @agunghide @azhargraha @rayfajars @yoslie @doohanas @rizfirman

Refactor : integration data management account complaint with axios

---

components/Aduan/AccountManagement/index.vue
components/Aduan/Dialog/Account/index.vue
components/Dialog/InformationNew/index.vue

-  integration api with axios
- change posititon emit close modal
- add function refresh data management account
title:   integration API with axios on form add account complaint
participants: @marsellavaleria19 @Ibwedagama @rizfirman

refactor : integration API with axios on form add account complaint

---

components/Aduan/Dialog/Account/index.vue
plugins/vee-validate.js

- fixing format email
- add validation numeric & limit on field NIP
title: fixing validation format email and field NIP  on form add account complaint
participants: @marsellavaleria19 @rizfirman @agunghide

fix : fixing validation format email and field NIP  on form add account complaint

---

components/Aduan/AccountManagement/index.vue

integration filter for search & role on page list
title: integration filter for search & role on page list management account complaint
participants: @marsellavaleria19 @doohanas @rizfirman @Ibwedagama

refactor: integration filter for search & role on page list management account complaint

---

components/Aduan/AccountManagement/Detail/index.vue
components/Aduan/AccountManagement/index.vue
constant/management-user.js
store/management-account.js

-  integration status & delete with API
- change status verified to active & add information dialog on constant management user
- add function show confirmation & information dialog on store management account
##Preview
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/ec263549-039b-4ede-82e6-eb54712fdb30
title: integration status delete management account complaint
participants: @marsellavaleria19 @rizfirman @azhargraha @Ibwedagama

refactor : integration update status and delete on feature management account complaint

---

components/Sribaduga/DialogTambahReservasi/index.vue

[CMS Sribaduga - Fungsi Tambah Sesi oleh Operator](https://app.clickup.com/t/86cuz4vu9)
Setup validation for tambah reservasi form
title: Setup validation for tambah reservasi form
participants: @rizfirman @Ibwedagama @marsellavaleria19 @agunghide @azhargraha

setup validation for tambah reservasi form

---

components/Sribaduga/DialogTambahReservasi/index.vue

[CMS Sribaduga - Fungsi Tambah Sesi oleh Operator
](https://app.clickup.com/t/86cuz4vu9)
improve border color of no. tlp & alamat instansi input when get errors
title: improve border color of no. tlp & alamat instansi input when get errors
participants: @rizfirman @agunghide @rayfajars @marsellavaleria19

improve border color of no. tlp & alamat instansi input when get errors

---

components/Aduan/AccountManagement/index.vue
constant/management-user.js

integration statistic & filter status with API
https://github.com/jabardigitalservice/super-app-cms/assets/44119106/adab1036-e88d-4914-908e-830a0b3f05e2
title: integration statistic & filter status with API on homepage management account complaint
participants: @marsellavaleria19 @rizfirman @agunghide @azhargraha @Ibwedagama

refactor: integration statistic & filter status with API on homepage management account complaint

---

components/Sribaduga/DialogDetailReservasi/index.vue
components/Sribaduga/DialogReschedule/index.vue
components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue
store/add_reservation.js

[CMS Sribaduga - Fungsi Tambah Sesi oleh Operator](https://app.clickup.com/t/86cuz4vu9)
slicing ui ubah reservasi form
title: slicing ui ubah reservasi form
participants: @rizfirman @Ibwedagama @agunghide @rayfajars @marsellavaleria19

slicing ui ubah reservasi

---

components/Aduan/Dialog/Account/index.vue
components/SectionMessage/index.vue

- add error section message on form add account management account complaint 
- change height component section message
title: fix : add error section message on form add account management account complaint 
participants: @marsellavaleria19 @rizfirman @rayfajars @azhargraha @sheilaazhara @Ibwedagama @agunghide

fix : add error section message on form add account management account complaint 

---

components/Base/DialogSlideRight/index.vue
components/Sribaduga/DialogTambahReservasi/index.vue

[CMS Sribaduga - Fungsi Tambah Sesi oleh Operator](https://app.clickup.com/t/86cuz4vu9)
create BaseDialogSlideRight component
title: create BaseDialogSlideRight component
participants: @rizfirman @marsellavaleria19 @rayfajars

create BaseDialogSlideRight component

---

components/Aduan/Dialog/Account/index.vue
components/Base/Button/index.vue
plugins/vee-validate.js

- fixing validation name & nip
- change component button using component base button
title: fixing validation name & nip on form management account complaint
participants: @marsellavaleria19 @yoslie @doohanas @rizfirman

Fix : fixing validation name & nip on form management account complaint

---

components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue

[CMS Sribaduga - Fungsi Tambah Sesi oleh Operator](https://app.clickup.com/t/86cuz4vu9)
remove overflow style in add ticket catagory button
title: remove overflow style in add ticket catagory button
participants: @rizfirman @sheilaazhara @agunghide @marsellavaleria19

remove overflow style in add ticket catagory button

---

layouts/Verification.vue
pages/verifikasi-email/index.vue

add layout verification on page email verification
title: add layout verification on page email verification
participants:  @marsellavaleria19 @agunghide @doohanas @rayfajars @rizfirman

refactor: add layout verification on page email verification

---

components/Sribaduga/KalenderReservasi/index.vue

[CMS Sribaduga - View Kalendar Reservasi
](https://app.clickup.com/t/86cuz4w50)
add query param for fetch calendar
title: add query param for fetch calendar
participants: @rizfirman @Ibwedagama @marsellavaleria19 @agunghide

add query param for fetch calendar

---

components/Aduan/AccountManagement/Detail/TableDetail/index.vue

add type dialog for resend email
title: add type dialog for resend email on page detail management account complaint
participants: @marsellavaleria19 @doohanas @agunghide @rizfirman

refactor : add type dialog for resend email on page detail management account complaint

---

components/Sribaduga/DialogBatalkanReservasi/index.vue
components/Sribaduga/DialogDetailReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue

[CMS Sribaduga - Mengembangkan Fitur Detail Daftar Pesanan
](https://app.clickup.com/t/86cuff1my)
create dialog batalkan reservasi
title: create dialog batalkan reservasi
participants: @rizfirman @agunghide @marsellavaleria19

create batalkan reservasi dialog

---

components/EmailVerification/index.vue
pages/verifikasi-email/index.vue

- integration email verification
- change button using hiperlink
title: integration verification email 
participants: @marsellavaleria19 @Ibwedagama @rizfirman @agunghide @yoslie @doohanas

Refactor : integration verification email 

---

components/Dialog/ConfirmationBasic/index.vue
components/Sribaduga/DialogBatalkanReservasi/index.vue

[CMS Sribaduga - Mengembangkan Fitur Detail Daftar Pesanan
](https://app.clickup.com/t/86cuff1my)
- create baseConfirmationDialogBasic component
- improve dialogBatalkanReservasi component
title: improve dialogBatalkanReservasi component
participants: @rizfirman @marsellavaleria19 @rayfajars @Ibwedagama @doohanas

create baseConfirmationDialogBasic and improve dialogBatalkanReservasi

---

pages/verifikasi-email/index.vue

add auth for accessible with/without authorization
title: add auth for accessible authorization on page email verification
participants: @marsellavaleria19 @yoslie @rayfajars @rizfirman

Refactor : add auth for accessible authorization on page email verification

---

components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue

[CMS Sribaduga - View Kalendar Reservasi](https://app.clickup.com/t/9003239225/CES-7995)
add new query param for get calendar event data
title: add new query param for get calendar event data
participants: @rizfirman @Ibwedagama @marsellavaleria19 @agunghide @doohanas

add new query param for get calendar event data

---

components/Aduan/AccountManagement/index.vue
components/Aduan/Dialog/Account/index.vue

[CES-9400 Memperbaiki fungsi button kirim ulang verifikasi email pada detail akun](https://app.clickup.com/t/9003239225/CES-9400)
-  initial variable id account to empty
- change propertu employee status
title: fixing function button resend email  on form resend email management account complaint
participants: @marsellavaleria19 @doohanas @rayfajars @agunghide @rizfirman

Fix : fixing function button resend email  on form resend email management account complaint

---

components/Sribaduga/DialogTambahReservasi/index.vue
constant/sribaduga.js
nuxt.config.js

[ CMS Sribaduga - Fungsi Tambah Sesi oleh Operator
](https://app.clickup.com/t/9003239225/CES-7993)
set function for post reservation data 
title: set function for post reservation data 
participants: @rizfirman @agunghide @rayfajars @marsellavaleria19

set function for post reservation data

---

components/Aduan/Dialog/Account/index.vue
components/Aduan/Dialog/AddComplaint/Form/InformationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Dialog/InputText/index.vue

add input type on some feature
title: add input type on some feature
participants: @marsellavaleria19 @azhargraha @agunghide @doohanas @rayfajars

refactor : add input type on some feature

---

pages/buat-password/index.vue

[Melakukan Integrasi API "Buat Kata Sandi"](https://app.clickup.com/t/9003239225/CES-9406)
- show spinner when loading
- integration with api
title:  integration with api on page create password
participants: @marsellavaleria19 @rayfajars @agunghide @doohanas

refactor : integration with api on page create password

---

middleware/guardRoutes.js

add page create password information for all roles
title: add page create password information for all roles
participants: @marsellavaleria19 @rayfajars @agunghide @yoslie @Ibwedagama

refactor: add page create password information for all roles

---

components/Sribaduga/DialogDetailReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue
components/Sribaduga/SkeletonLoadingDetailReservasi/index.vue

[ CMS Sribaduga - Fungsi Resechedule Sesi](https://app.clickup.com/t/9003239225/CES-7994)
- reservation detail integration
title: reservation detail integration
participants: @rizfirman @rayfajars @doohanas @marsellavaleria19

reservation detail integration

---

pages/verifikasi-email/index.vue

change wording for page link verification invalid
title: change wording for page link verification invalid
participants: @marsellavaleria19 @rayfajars @doohanas @agunghide

refactor: change wording for page link verification invalid

---

components/SectionMessage/index.vue
pages/lupa-kata-sandi/index.vue

- integration with api
- show error message with section message
- show spinner for loading
title:  integration page forgot password
participants: @marsellavaleria19 @doohanas @yoslie @rayfajars

Refactor : integration page forgot password

---

pages/cek-email/index.vue
pages/lupa-kata-sandi/index.vue

- add action close section message
-  integration with api on page check email
title: integration with api on page check email
participants: @marsellavaleria19 @agunghide @azhargraha @rayfajars

Refactor : integration with api on page check email

---

components/Base/Dialog/Frame/index.vue
components/Sribaduga/DialogReschedule/index.vue
components/Sribaduga/DialogSuccess/index.vue
components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue

[CMS Sribaduga - Fungsi Resechedule Sesi](https://app.clickup.com/t/9003239225/CES-7994)
- create success dialog for sribaduga page
title: create success dialog for sribaduga page
participants: @rizfirman @marsellavaleria19 @azhargraha @doohanas

create success dialog for sribaduga page

---

nuxt.config.js
pages/buat-password/index.vue

[Melakukan validasi expired invitation token - Lupa Password](https://app.clickup.com/t/9003239225/CES-10153)
- add env link expired time
- add condition when show page information link expired
title: show page information link expired on page create password
participants: @marsellavaleria19 @rizfirman @agunghide @azhargraha @rayfajars

Refactor : show page information link expired on page create password

---

pages/buat-password/index.vue

change class config for link expired time
title: change class config link expired time on page create password
participants: @marsellavaleria19 @rayfajars @doohanas

Refactor : change class config link expired time on page create password

---

pages/buat-password/index.vue
pages/lupa-kata-sandi/index.vue

- change error wording when send email
title: change error wording when send email
participants: @marsellavaleria19 @rayfajars @doohanas

refactor: change error wording when send email

---

components/Sribaduga/DialogTambahReservasi/index.vue

[ CMS Sribaduga - Fungsi Tambah Sesi oleh Operator](https://app.clickup.com/t/9003239225/CES-7993)
- add minimum person validation when add reservation sribaduga
title: add minimum person validation when add reservation sribaduga
participants: @rizfirman @Ibwedagama @marsellavaleria19 @rayfajars @yoslie

add minimum person validation when add reservation sribaduga

---

pages/verifikasi-email/index.vue

[[FE] CMS Aduan - Link verifikasi - Buat password baru masih dapat digunakan setelah user verified](https://app.clickup.com/t/9003239225/CES-10257)
- fixing condition integration with api when authentication true
title: fixing condition integration with api on page email verification
participants: @marsellavaleria19 @rizfirman @azhargraha @doohanas @agunghide @Ibwedagama

fix: fixing condition integration with api on page email verification

---

pages/verifikasi-email/index.vue

change wording link expired on page email verification
title:  change wording for link expired on page email verification
participants: @marsellavaleria19 @azhargraha @rayfajars @yoslie @doohanas

refactor : change wording for link expired on page email verification

---

components/Sribaduga/DialogReschedule/index.vue
components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue
plugins/vee-validate.js

[ CMS Sribaduga - View Kalendar Reservasi](https://app.clickup.com/t/9003239225/CES-7995)
- add phone validation and improve calendar session event layout 
title: add phone validation and improve calendar session event layout 
participants: @rizfirman @marsellavaleria19 @agunghide

add phone validation and improve calendar session event layout

---

components/Sribaduga/LaporanPendapatan/index.vue
constant/sribaduga.js

-  filtering 'all' data in listKunjunganSribaduga & listCategoryStatus 
title:  filtering 'all' data in listKunjunganSribaduga & listCategoryStatus 
participants: @rizfirman @marsellavaleria19 @azhargraha @doohanas

fix: filtering 'all' data in listKunjunganSribaduga & listCategoryStatus

---

constant/menuList.js

change some unleash variable name on feature complaint
title: change some unleash variable name on feature complaint
participants: @marsellavaleria19 @rizfirman @agunghide

refactor: change some unleash variable name on feature complaint

---

components/Sribaduga/KalenderReservasi/index.vue

[[CMS] Sribaduga - List issue Kalender Reservasi](https://app.clickup.com/t/9003239225/CES-10574)
- fetch holiday list api
title: fetch holiday list api
participants: @rizfirman @marsellavaleria19 @azhargraha

feat: fetch holiday list api

---

components/Sribaduga/DialogReschedule/index.vue
components/Sribaduga/DialogTambahReservasi/index.vue
components/Sribaduga/KalenderReservasi/index.vue
components/Sribaduga/LaporanPendapatan/index.vue
store/add_reservation.js

[[CMS] Sribaduga - List issue Kalender Reservasi](https://app.clickup.com/t/9003239225/CES-10574)
- show error message when reschedule/add reservation error
title: show error message when reschedule/add reservation error
participants: @rizfirman @rayfajars @yoslie @doohanas

show error message when reschedule/add reservation error

---

middleware/guardRoutes.js

- fixing redirect link when login as admin sribaduga
title: fixing redirect link when login as admin sribaduga
participants: @rizfirman @marsellavaleria19 @azhargraha @rayfajars @doohanas

fixing redirect link when login as admin sribaduga

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Aduan/index.vue
constant/aduan-masuk.js
constant/daftar-ikp.js
constant/menuList.js
pages/aduan/instruksi-kewenangan-pemprov/detail-ikp/_id/index.vue
pages/aduan/instruksi-kewenangan-pemprov/detail/_id/index.vue
pages/aduan/instruksi-kewenangan-pemprov/index.vue

[CES-10724 Melakukan perubahan nama Menu "Daftar Penginputan IKP"](https://app.clickup.com/t/9003239225/CES-10724)
- update complaint type from constant
- change complaint type for government authority instruction
- update menu to government authority instruction
- add page government authority instruction
title: update menu to government authority instruction
participants: @marsellavaleria19 @rayfajars @agunghide @Ibwedagama @azhargraha

Refactor : update menu to government authority instruction

---

components/Aduan/index.vue
pages/aduan/instruksi-kewenangan-non-pemprov/index.vue

- add button action for create instruction
- change link page detail
title: add button action & change link page detail on feature non government authority instruction
participants: @marsellavaleria19 @rayfajars @rizfirman

Refactor : add button action & change link page detail on feature non government authority instruction

---

components/Aduan/Detail/Table/Complaint/index.vue

- add function for complaint status text
title: refactor add function for complaint status text
participants: @marsellavaleria19 @agunghide @rizfirman @Ibwedagama

refactor: add function for complaint status text

---

components/Sribaduga/DialogDetailReservasi/index.vue

add comment in dialog detail reservasi

---

components/Aduan/Detail/index.vue

- add condition show tab complaint instruction for status has coordinated
title: Refactor show tab complaint instruction on page detail non government authority
participants: @marsellavaleria19 @rizfirman

Refactor : show tab complaint instruction on page detail non government authority

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/Detail/index.vue
constant/daftar-ikp.js
pages/aduan/instruksi-kewenangan-non-pemprov/detail/_id/index.vue

- integration complaint instruction & change width on data table
- update function for back to main page
- remove navigation detail instruction for breadcrumb
- add instruction status & show on page detail
- change name tab for instruction of complaint
title: Refactor integration some field on page detail instruction of complaint non government authority instruction
participants: @marsellavaleria19 @agunghide @rizfirman @yoslie

Refactor : integration some field on page detail instruction of complaint non government authority instruction

---

components/Aduan/Dialog/ProcessComplaint/index.vue
components/Base/TextArea/index.vue

[Menyesuaikan tampilan form proses aduan status dikoordinasikan](https://app.clickup.com/t/9003239225/CES-12107)
[Menyesuaikan tampilan form proses aduan status dialihkan ke sp4n lapor](https://app.clickup.com/t/9003239225/CES-12119)
- add helper text on component base text area
- update some field on form complaint process
title: update some field on form complaint process
participants: @marsellavaleria19 @rizfirman @agunghide @rayfajars

Feat : update some field on form complaint process

---

components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
components/Sidebar/index.vue
mixins/popup-aduan-masuk.js
store/process-complaint.js

[Membuat tampilan form ubah kewenangan](https://app.clickup.com/t/9003239225/CES-12355)
- add function for show form change authority
- set titile and button form change authority
- set data complaint to showing field on form change authority 
title: show layout form change authority
participants: @marsellavaleria19 @rizfirman @yoslie @doohanas

refactor: show layout form change authority

---

components/Aduan/Alert/Information/index.vue
components/Aduan/Dialog/CreateIkp/CardIkpNarrative/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/Pagination/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/IkpNarrative/index.vue
components/Aduan/index.vue
mixins/popup-aduan-masuk.js
store/create-ikp.js

[Membuat tampilan dialog "Buat Instruksi Aduan Baru"](https://app.clickup.com/t/9003239225/CES-12534)
- change title dialog ikp narrative
-  add function for show dialog create instruction
- slicing layout new form create instruction
- fixing margin icon on table pagination followup instruction
-  add field id span lapor & payload for form create instruction
- fixing show icon information for alert information
-  add payload on store create ikp
title: slicing layout form create instruction for feature non government authority instruction
participants: @marsellavaleria19 @Ibwedagama @rizfirman @rayfajars @doohanas

Feat : slicing layout form create instruction for feature non government authority instruction

---

components/Aduan/Dialog/ProcessComplaint/index.vue
store/process-complaint.js

- show & hide some field when coverage of affairs is district 
- add attribute payload opd_pemprov_id on store process complaint
https://github.com/user-attachments/assets/637fd169-27f1-46ca-9950-4f3c05bbe08c
title: show and hide some field & add attribute payload for government responsible on form process complaint
participants: @marsellavaleria19 @rayfajars @rizfirman

Refactor : show and hide some field & add attribute payload for government responsible on form process complaint

---

components/Aduan/Dialog/ProcessComplaint/index.vue
mixins/popup-aduan-masuk.js

- add condition for data dialog information change authority
title: add condition for data dialog information change authority
participants: @marsellavaleria19 @yoslie @rizfirman @agunghide @doohanas

refactor : add condition for data dialog information change authority

---

components/Aduan/Dialog/CreateIkp/Dialog/Information/index.vue
components/Aduan/Dialog/CreateIkp/Dialog/WithAlert/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
mixins/popup-aduan-masuk.js

- update content & title dialog confirmation & information on form create new instruction
- add function for close pop confirmation for dialog followup complaint 
-  update title & description dialog information on dialog followup complaint  
title: refactor update title & description on dialog confirmation and information form create instruction
participants: @marsellavaleria19 @Ibwedagama @rizfirman @rayfajars @yoslie @doohanas

Refactor : update title & description on dialog confirmation and information form create instruction

---

components/Aduan/index.vue
components/Base/Tab/index.vue
components/Sidebar/Item.vue
components/Sidebar/index.vue
layouts/Dashboard.vue

[[CMS] Aduan Warga - Instruksi Kewenangan non-pemprov -Layout tabel terpotong dengan resolusi 100%](https://app.clickup.com/t/9003239225/CES-11668)
- fix padding on component sidebar
- fixing width for responsive on component complaint
- fixing padding base content layout
- fixing width & style code on component base tab
- fixing style item sidebar
title: fixing style for display responsive
participants: @marsellavaleria19 @rizfirman @yoslie @doohanas

Fix : fixing style for display responsive

---

components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
mixins/popup-aduan-masuk.js

[[Revisi]Aduan Pemprov - form buat instruksi aduan](https://app.clickup.com/t/9003239225/CES-12656)
-  add data complaint on mixins
-  change position data complaint on function show popup create instruction
-  disabled some field & clear field for instruction note on form new instruction
title: disabled some field form new instruction for government instruction authority
participants: @marsellavaleria19 @rizfirman @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/TpI9lP

Feat : disabled some field form new instruction for government instruction authority

---

components/Aduan/DaftarIKP/index.vue

[[CMS Aduan] Search bar logic](https://app.clickup.com/t/9003239225/CES-13380)
fixing search bar logic on page list
title: fixing search bar logic on page list complaint instruction non government
participants: @marsellavaleria19 @Ibwedagama @rizfirman @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/2uvqqV

fix : fixing search bar logic on page list complaint instruction non government

---

components/Aduan/index.vue
constant/endpoint-api.js

[[CMS] Aduan Warga - Daftar Aduan Masuk - Penyesuaian tampilan dan perubahan data -> Menunggu Verifikasi](https://app.clickup.com/t/9003239225/CES-13544)
- fixing default sorting by updated_at
- add constant for endpoint api complaint
title: Fix default sorting by updated at on page list complaints incoming
participants: @marsellavaleria19 @agunghide @rizfirman 
screenshot: https://s.digitalservice.id/IObcqB

Fix : default sorting on page list complaints incoming

---

components/Aduan/DialogViewImage/index.vue

- add function for download image
title: add function for download image
participants: @marsellavaleria19 @rayfajars @rizfirman 
screenshot: https://s.digitalservice.id/3m2qO0

feat : add function for download image

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/DaftarIKP/index.vue
components/Aduan/Detail/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/Dialog/TrackingSpanLapor/index.vue
components/Aduan/index.vue
constant/endpoint-api.js
mixins/popup-aduan-masuk.js
store/add-complaint.js

change endpoint api on all feature complaints
title: refactor change endpoint api on all feature complaints
participants: @marsellavaleria19 @doohanas @rayfajars @sheilaazhara 
screenshot: https://s.digitalservice.id/YzJe9X

refactor : change endpoint api on all feature complaints

---

components/Aduan/Dialog/ProcessComplaint/index.vue
constant/endpoint-api.js

[[CMS] Aduan Warga - Daftar Penentu Kewenangan - proses - penyesuaian tingkat urgensi](https://app.clickup.com/t/9003239225/CES-13614)
adjusting the level of urgency for clear date on form determining authority
title: fix adjusting the level of urgency for clear date on form determining authority
participants: @marsellavaleria19 @yoslie @rizfirman @sheilaazhara 
screenshot: https://s.digitalservice.id/V5dXrb

fix : adjusting the level of urgency for clear date on form determining authority

---

components/Aduan/Dialog/CreateIkp/index.vue
constant/endpoint-api.js

change endpoint api for feature complaint
title: Fix change end point api for feature complaint
participants: @marsellavaleria19 @doohanas @agunghide @rizfirman 
screenshot: https://s.digitalservice.id/u5CrsD

Fix : change end point api for feature complaint

---

components/Aduan/index.vue
components/Base/Dialog/FooterNew/index.vue
components/Dialog/InputTextArea/index.vue
mixins/popup-aduan-masuk.js

[[CMS Aduan]User Tim 1 Melakukan aksi Dialihkan ke Hotline Jabar](https://app.clickup.com/t/9003239225/CES-13751)
- update function name for redirect to hotline jabar
- add function for show popup confirmation failed & redirect to hotline jabar
- fixing label name for cancel button
- add some changes for disable button on dialog input text area
title: feat slicing popup confirmation redirect hotline jabar
participants: @marsellavaleria19  @rizfirman @doohanas 
screenshot: https://s.digitalservice.id/XIVLNr

feat : slicing popup confirmation redirect hotline jabar

---

components/Aduan/Detail/index.vue
components/Base/ButtonDropdown/index.vue
constant/aduan-masuk.js

[[CMS Aduan] Menambahkan Detail Aduan pada Tab Dialihkan ke Hotline Jabar](https://app.clickup.com/t/9003239225/CES-13735)
- change button action & show directed to hotline jabar note
- fixing popover content on base component button dropdown
- remove data some data button detail on file constant
title: Feat add field for status directed to hotline jabar on detail page feature complaint incoming
participants: @marsellavaleria19 @Ibwedagama @rizfirman @rayfajars @yoslie @doohanas 
screenshot: https://s.digitalservice.id/Vu3pBG

Feat : add field for status directed to hotline jabar on detail page feature complaint incoming

---

mixins/popup-aduan-masuk.js

fix remove quote one on function submit popup complaint]
title: fix remove quote one on function submit popup complaint
participants: @marsellavaleria19 @rayfajars @sheilaazhara @Ibwedagama @rizfirman 
screenshot: https://s.digitalservice.id/ZzWKxI

fix : remove quote one on function submit popup complaint

---

components/Aduan/Dialog/FollowupHotlineJabar/index.vue
components/Aduan/index.vue
components/Base/Dialog/Description/index.vue
components/Dialog/ConfirmationBasic/index.vue
components/Dialog/InformationNew/index.vue
constant/aduan-masuk.js
store/popup-complaint.js

[[CMS Aduan] Menampilkan Aksi Tindaklanjuti Aduan Hotline Jabar](https://app.clickup.com/t/9003239225/CES-13738)
- add dialog fom hotline jabar
- add state management for popup complaint
- add action for show popup dialog form hotline jabar
- add dialog confirmation, information & loading
title: Feat slicing dialog form followup hotline jabar
participants: @marsellavaleria19 @Ibwedagama @yoslie 
screenshot: https://s.digitalservice.id/SnMRZJ

Feat : slicing dialog form followup hotline jabar

---

components/Aduan/Dialog/EvidenceFollowupHotline/index.vue
components/Aduan/Dialog/FollowupHotlineJabar/index.vue
components/Aduan/index.vue
components/Base/DragAndDropFile/index.vue
store/index.js
store/popup-complaint.js

[[CMS Aduan] Menambahkan Detail Status Tindaklanjuti Aduan Hotline Jabar](https://app.clickup.com/t/9003239225/CES-13739)
- add form dialog evidence followup hotline jabar
- add state response file on state management
- add state data dialog confirmation & data dialog information on state management popup complaint 
title: Feat slicing layout form evidence followup hotline jabar
participants: @marsellavaleria19 @rizfirman @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/kp49CV

Feat : slicing layout form evidence followup hotline jabar

---

components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Aduan/Dialog/EvidenceFollowupHotline/index.vue
constant/aduan-masuk.js
pages/aduan/aduan-hotline-jabar/detail/_id/index.vue

[[CMS Aduan] Menambahkan Detail Status Tindaklanjuti Aduan Hotline Jabar](https://app.clickup.com/t/9003239225/CES-13739)
- add page detail hotline jabar
- add button & data complaint source
- fixing width for feature hotline jabar
- update format type & information format on dialog upload evidence hotline jabar
title: feat slicing layout page detail hotline jabar
participants:  @marsellavaleria19 @agunghide @azhargraha @rayfajars 
screenshot: https://s.digitalservice.id/sgKfbl

Feat : slicing layout page detail hotline jabar

---

components/Aduan/Dialog/EvidenceFollowupHotline/index.vue

[feat : add type image png](https://github.com/jabardigitalservice/super-app-cms/commit/2a1de9368b96407dde37f20890677195a5147297)
title: feat add type image png on form evidence followup hotline 
participants: @marsellavaleria19 @rayfajars @rizfirman 
screenshot: https://s.digitalservice.id/F6EDe9

feat : add type image png on form evidence followup hotline 

---

components/Aduan/index.vue

[feat : add phase for integration statiistic with api](https://github.com/jabardigitalservice/super-app-cms/commit/c06f59c2a557fa4f68aeb0e488f2cea6592e2028)
title: feat add phase for integration statiistic with api
participants: @marsellavaleria19 @rizfirman @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/JQXGhf

feat : add phase for integration statiistic with api

---

components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Aduan/index.vue

change attribute complaint_source to object
title: refactor change attribute complaint source to object
participants: @marsellavaleria19 @agunghide @rayfajars @doohanas 
screenshot: https://s.digitalservice.id/tBmZQB

refactor : change attribute complaint_source to object

---

components/Aduan/Dialog/EvidenceFollowupHotline/index.vue

[add attribute name on files payload](https://github.com/jabardigitalservice/super-app-cms/commit/5de866cffb7d9249abc9ba067feab209300548d9)
title: Feat add attribute name on payload files evidence follow up hotline
participants: @marsellavaleria19 @rizfirman @agunghide @rayfajars @yoslie 
screenshot: https://s.digitalservice.id/toqTYy

Feat : add attribute name on payload files evidence follow up hotline

---

components/Aduan/index.vue

[add dialog loading](https://github.com/jabardigitalservice/super-app-cms/commit/72832b74feef0a70bd1e6769d898b19b9b393345)
title: feat add dialog loading on component complaints
participants: @marsellavaleria19 @Ibwedagama @rizfirman @azhargraha @rayfajars @doohanas 
screenshot: https://s.digitalservice.id/ZB8kn1

feat : add dialog loading on component complaints

---

components/Aduan/Detail/index.vue
components/Aduan/Dialog/EvidenceFollowupHotline/index.vue
components/Aduan/Dialog/FollowupHotlineJabar/index.vue
components/Aduan/index.vue
mixins/popup-aduan-masuk.js

[feat : add variable url api](https://github.com/jabardigitalservice/super-app-cms/commit/c0182c97eb1ec280bf6f1a99074d99132013bc28)
[feat : add emit close modal & fetch](https://github.com/jabardigitalservice/super-app-cms/commit/0547b7eef5f87f5d945c116b0f33bd7c2438aa79)
[feat : add query page on function closepopup information](https://github.com/jabardigitalservice/super-app-cms/commit/4769bf91e0c17e90cb991fe4b0e10b4e21a46ef8)
[feat : add function show popup evidence followup hotline jabar](https://github.com/jabardigitalservice/super-app-cms/commit/8f7aafcb8875f16ac79842766f086d2e4bad4695)
[fix : change url logo complaint source using api on dialog form followup hotlone](https://github.com/jabardigitalservice/super-app-cms/commit/bbed85995869c59a9aae5dcdf472ef947741fc12)
title: Feat …

Feat : add url api & function for refresh data

---

components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
mixins/popup-aduan-masuk.js

- fixing condition disable date
- remove different from created at
- change complaint source using response api
- add dialog confirmation
- add function popup confirmation & back to form
title: condition disabled filled deadline date & add popup confirmation on form process complaint
participants: @marsellavaleria19 @rizfirman @yoslie 
Lampiran: https://s.digitalservice.id/NSXTRF

Fix : condition disabled filled deadline date & add popup confirmation on form process complaint

---

components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Aduan/index.vue

[fix : show tab status not show when filter data on component page list](https://github.com/jabardigitalservice/super-app-cms/commit/6fdc914c75dc1fd0dc0450825000ddd3b9739aa9)
[fix : format deadline date on component detail complaint](https://github.com/jabardigitalservice/super-app-cms/commit/51c3fa9782dcec87e79191d115a76b1b86f43e32)
title:  fixing layout tab status on page list & format deadline date on detail page determining authority
participants: @marsellavaleria19 @Ibwedagama @sheilaazhara @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/xiCppb

Fix : fixing layout tab status on page list & format deadline date on detail page determining authority

---

components/Aduan/Dialog/CreateIkp/CardIkpNarrative/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Base/Dialog/Description/index.vue
mixins/popup-aduan-masuk.js

[fix : data not show](https://github.com/jabardigitalservice/super-app-cms/commit/9084e982094e5571edff8d0a00697460b223c41c)
[fix : change text color](https://github.com/jabardigitalservice/super-app-cms/commit/1613494c9ec0c1a0f557380e852e394cb8b6a888)
title: fix data not show & text color on form followup complaint
participants: @marsellavaleria19 @rayfajars @rizfirman @agunghide 
screenshot: https://s.digitalservice.id/gjWFpc

Fix : data not show & text color on form followup complaint

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/DaftarIKP/index.vue
components/Aduan/Detail/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
constant/aduan-masuk.js
constant/daftar-ikp.js
mixins/popup-aduan-masuk.js
pages/aduan/instruksi-kewenangan-non-pemprov/detail/_id/index.vue
pages/aduan/instruksi-kewenangan-non-pemprov/index.vue
store/create-ikp.js
store/process-complaint.js

- change phase to authorization
- change key complaints_count to complaints_total
-  remove opd_name & add opd_id
- add payload is_prov_responsibility on form create ikp
- change key jumlah aduan to complaint_total on constant daftar ikp
title: fixing some issue on featureinstruction complaint
participants: @marsellavaleria19 @rizfirman @rayfajars  
screenshot: https://s.digitalservice.id/pTilvX

Fix : fixing some issue on featureinstruction complaint

---

components/Aduan/index.vue

[fix : searching with space on some feature complaint](https://github.com/jabardigitalservice/super-app-cms/commit/5a2a4d7dd1c85ed4b0dc6cd43302724be836f8d7)
title: fix issue searching with space not show on some feature complaint
participants: @marsellavaleria19 @rayfajars @azhargraha @agunghide @Ibwedagama 
screenshot: https://s.digitalservice.id/95dqXO

fix : issue searching with space not show on some feature complaint

---

components/KlaimRW/index.vue
nuxt.config.js

handle new relic in staing and development
title: add condition new relic staging and dev
participants: @rayfajars @doohanas @azhargraha @rizfirman

feat: add condition new relic staging and dev

---

components/Dialog/ConfirmationNew/index.vue
components/MessageNotif/Form/index.vue

fix flow upload image message blast
title: fix changes flow upload iamge blast message
participants: @rayfajars @rizfirman @marsellavaleria19

fix: changes flow upload iamge blast message

---

components/Aduan/Dialog/ProcessComplaint/index.vue

[clear field on dialog form process complaint](https://github.com/jabardigitalservice/super-app-cms/commit/029f2d3b5d305c03690e9023f51ab522b19179f0)
title: fix clear field on dialog form process complaint
participants: @marsellavaleria19 @doohanas @sheilaazhara @rizfirman @Ibwedagama 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzMxNjQ0ODM5NzY1LTAuMzIzNTM2NjM0MTM2ODMwMi53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9Q1F5Um1QRTBrdkpqa0h0ZyUyRjIwMjQxMTE1JTJGYXNpYS1zb3V0aGVhc3QyLWElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA0MjcxOVomWC1BbXotRXhwaXJlcz02MDQ4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JlgtQW16LVNpZ25hdHVyZT0xNWZlOWI0Mjc0MjJlZmQxMzRmZmEzOD …

fix : clear field on dialog form process complaint

---

components/Dialog/InputText/index.vue
constant/aduan-masuk.js
mixins/popup-aduan-masuk.js
store/popup-complaint.js

[fix : add condition clear field on component doalog input text](https://github.com/jabardigitalservice/super-app-cms/commit/9cc1becfc9a7e9d5c683fa9b0b46cb634d8169e5)
title: fix add condition clear field on component doalog input text
participants: @marsellavaleria19 @rayfajars @Ibwedagama 
screenshot: https://s.digitalservice.id/m9UaW1

fix : add condition clear field on component doalog input text

---

components/Aduan/Dialog/AddComplaint/Form/InformationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/LocationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/AddComplaint/index.vue
components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
components/Dialog/InformationNew/index.vue
components/Dialog/WithStepper/index.vue
mixins/popup-aduan-masuk.js
store/add-complaint.js
store/utilities-complaint.js

[fix : ssue double fetch utilities](https://github.com/jabardigitalservice/super-app-cms/commit/2cd6f621fd4f353e0ca381d0086a693593adea64)
[fix : some issue on form add complaint](https://github.com/jabardigitalservice/super-app-cms/commit/08e6b806947fdb6d71c1eccfe4535eae269133bc)
[feat : add state management for utilities](https://github.com/jabardigitalservice/super-app-cms/commit/640b69675f7faa250170e99d6ff80eb8c23bf083)
title: fix issue double fetching utilities
participants: @marsellavaleria19 @yoslie @rayfajars @rizfirman @Ibwedagama 
screenshot: https://s.digitalservice.id/fBoSvm

Fix : issue double fetching utilities

---

components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/index.vue
mixins/popup-aduan-masuk.js
store/create-ikp.js
store/followup-complaint.js
store/utilities-complaint.js

[fix : add complaint type on form followup complaint & create ikp](https://github.com/jabardigitalservice/super-app-cms/commit/b16358fe493cb805c5bff745892d85182ed217d2)
[fix : change url api for complaint status non government](https://github.com/jabardigitalservice/super-app-cms/commit/e80f3f049c10538b3a9801ba8c839add9da59605)
[fix : add payload complaint number & condition endpoint url non pemprov](https://github.com/jabardigitalservice/super-app-cms/commit/fcc79551060517e6f513dfc323c7e17d254bec5f)
title: Fix issue add span id and feature instruction non government authorities
participants: @marsellavaleria19 @yoslie @rayfajars @Ibwedagama 
screenshot: https://s.digitalservice.id/5bSsmc

Fix : issue add span id and feature instruction non government authorities

---

components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/index.vue
mixins/popup-aduan-masuk.js

[fix : show select all complaint status on component complaint](https://github.com/jabardigitalservice/super-app-cms/commit/e5a9cbb0a7cd191073c65ee59b408399fb014622)
[feat : add state is_prov_responsibility on component dialog followup complaint](https://github.com/jabardigitalservice/super-app-cms/commit/67a5268b154ff7bcdeca6968992659cc91b1eb7e)
[feat : add data dialog error information on mixins popup aduan masuk](https://github.com/jabardigitalservice/super-app-cms/commit/411574532f32695859011d5220f1ec92b8e2ed1d)
title: Fix issue popup information add id span and filter instruction on form followup complaint
participants: @marsellavaleria19 @yoslie @rayfajars @Ibwedagama 
screenshot: https://s.digitalservice.id/sEgBLW

Fix : issue popup information add id span and filter instruction on form followup complaint

---

components/Aduan/Dialog/AddComplaint/Form/LocationComplaint/index.vue
store/add-complaint.js

[feat: add payload location name](https://github.com/jabardigitalservice/super-app-cms/commit/7b8d3e05e4c4205e2cc7010c085980a4ea917415)
title: feat add payload location name on form add complaint
participants: @marsellavaleria19 @rayfajars @rizfirman 
screenshot: https://s.digitalservice.id/n8qqva

feat: add payload location name on form add complaint

---

components/Aduan/DaftarIKP/TableDetail/index.vue
components/Aduan/DaftarIKP/index.vue
components/Aduan/Detail/Table/Complaint/index.vue
components/Aduan/Detail/index.vue
components/Dialog/InformationNew/index.vue
constant/aduan-masuk.js
constant/daftar-ikp.js
pages/aduan/instruksi-aduan-warga/detail-aduan/_id/index.vue
store/add-complaint.js

[fix : issue data instruction not show](https://github.com/jabardigitalservice/super-app-cms/commit/76a292cb1272cd5122d8ca65dafdf9fdecd8b9f7)
[fix : issue data other complaint not reset](https://github.com/jabardigitalservice/super-app-cms/commit/dbae5a406af448dba9e4d020f1c2b9a21080cddf)
title: Fix issue data instruction not show & data other complaint not reset on form add sp4n
participants: @marsellavaleria19 @rayfajars 
screenshot: https://s.digitalservice.id/V1oaeH

Fix : issue data instruction not show & data other complaint not reset on form add sp4n

---

mixins/popup-aduan-masuk.js

[fix : issue show error description id span](https://github.com/jabardigitalservice/super-app-cms/commit/66424b9644842abd97f093402ddf472668763357)
title: Fix issue show error description id span
participants: @marsellavaleria19 @rizfirman @rayfajars @agunghide 
screenshot: https://s.digitalservice.id/NYRdIX

fix : issue show error description id span

---

components/Dialog/InformationNew/index.vue
components/MessageNotif/Form/index.vue

- add copy_paste_text in tiny mce
- remove close modal on retry submit
title: feat remove reset image and remove close modal name
participants: @rayfajars @doohanas @agunghide @sheilaazhara @marsellavaleria19

feat: remove reset image and remove close modal name

---

components/Aduan/Dialog/ProcessComplaint/index.vue
components/Dialog/InputText/index.vue
mixins/popup-aduan-masuk.js
store/process-complaint.js
store/utilities-complaint.js

[fix : issue show & clear payload on feature determining authority](https://github.com/jabardigitalservice/super-app-cms/commit/05d8489373385b28609aa622b5f8c696c17d9d82)
[fix : reset filed on component dialog input text](https://github.com/jabardigitalservice/super-app-cms/commit/b5f8bc82e6a9a78887128f97aeb49e56ceb158c9)
title: Fix issue show clear data form feature determining authority
participants: @marsellavaleria19 @rayfajars @yoslie 
screenshot: https://s.digitalservice.id/6DzMB0

Fix : issue show clear data form feature determining authority

---

components/Aduan/Dialog/ProcessComplaint/index.vue
components/Dialog/InputText/index.vue
mixins/popup-aduan-masuk.js
store/process-complaint.js
store/utilities-complaint.js

[refactor : change attribute error instruction](https://github.com/jabardigitalservice/super-app-cms/commit/c561b8f5abffe937bee5bce81097169d1e92d50c)
title: refactor change attribute error instruction
participants: @marsellavaleria19 @yoslie 
screenshot: https://s.digitalservice.id/ZRbKUw

refactor : change atribute error instruction

---

constant/daftar-ikp.js

[fix : remove some field on section others page detail instruction non gov](https://github.com/jabardigitalservice/super-app-cms/commit/b6ab8b3cc94cd2f69b918b91b979c4866bb850be)
title: fix remove some field on section others page detail instruction non government
participants: @marsellavaleria19 @rayfajars @agunghide 
screenshot: https://s.digitalservice.id/MToTw3

fix : remove some field on section others page detail instruction non government

---

components/Aduan/Dialog/FollowupComplaint/index.vue

[fix : add query params range date & add column complaint status](https://github.com/jabardigitalservice/super-app-cms/commit/7ffea1414e863281f5e4705b09cc9a876a8aafd4)
title: fix add query params range date & add column complaint status on component followup complaint
participants: @marsellavaleria19 @rizfirman 
screenshot: https://s.digitalservice.id/2UBhBK

fix : add query params range date & add column complaint status on component followup complaint

---

components/Aduan/Dialog/TrackingSpanLapor/CardSpanLapor/index.vue

[fix: layout card dialog tracking span lapor](https://github.com/jabardigitalservice/super-app-cms/commit/d6f21a99cc0e20ad9ce8a0038679d6ad898b0a13)
title: fix layout card dialog tracking span lapor
participants: @marsellavaleria19 @yoslie @rayfajars @agunghide 
screenshot: https://s.digitalservice.id/YFiIj7

fix: layout card dialog tracking span lapor

---

components/Aduan/Detail/index.vue
mixins/popup-aduan-masuk.js

[fix : show dialog process & followup complaint](https://github.com/jabardigitalservice/super-app-cms/commit/cbe8191aa3f00649a6ea708dd25c7d6ca44e177d)
title: fix show dialog process & followup complaint on component complaint detail
participants: @marsellavaleria19 @rizfirman @agunghide 
screenshot: https://s.digitalservice.id/XRfVXL

fix : show dialog process & followup complaint on component complaint detail

---

components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue

[fix : show validation error on field sub category](https://github.com/jabardigitalservice/super-app-cms/commit/ff6949f7b9d637072dca23c3917a8353c701c0c3)
title: fix show validation error on field sub category form add complaint
participants: @marsellavaleria19 @rayfajars 
screenshot: https://s.digitalservice.id/GiHuJn

fix : show validation error on field sub category form add complaint

---

components/Aduan/DaftarIKP/index.vue
components/Aduan/Dialog/AddComplaint/index.vue
components/Aduan/Dialog/EvidenceFollowupHotline/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
components/Dialog/WithStepper/index.vue

- fix responsive layout component complaint
- fix change responsive width & add truncate on component instruction
- fix responsive dialog form height on some dialog form complaint
title: Fix responsive layout on feature complaint and instruction
participants: @marsellavaleria19  @doohanas @rayfajars 
screenshot: https://s.digitalservice.id/vaC9LT

Fix : responsive layout on feature complaint and instruction

---

components/Aduan/Detail/Table/Complaint/index.vue
pages/aduan/aduan-dari-span-lapor/detail/_id/index.vue

[fix : show category & subcategory complaint](https://github.com/jabardigitalservice/super-app-cms/commit/26841016c19c7af2aa8a6a0d45a483694a9e41b2)
[fix : remove props list-button](https://github.com/jabardigitalservice/super-app-cms/commit/ddbb7ec791c219d02e37811489ad998a025d98d2)
title: Fix show categori and subcategory complaint on component detail complaint
participants: @marsellavaleria19 @doohanas @yoslie @rayfajars @agunghide @sheilaazhara @rizfirman 
screenshot: https://s.digitalservice.id/mLsXV8

Fix : show category and subcategory complaint on component detail complaint

---

components/Aduan/TabBar/List/index.vue
components/Aduan/index.vue
components/Base/TableAction/index.vue

- add data-cy for tab & button action on component complaint
- add data-cy on component tab bar complaint
- add data-cy on for dropdown button action
title: Feat add data cy on page list complaint income
participants: @marsellavaleria19 @rayfajars @doohanas @yoslie 
screenshot: https://s.digitalservice.id/zwjWJp

Feat : add data cy on page list complaint income

---

components/Base/Dialog/Footer/index.vue
components/Dialog/Confirmation/index.vue
components/Dialog/Information/index.vue
mixins/popup-aduan-masuk.js

[feat : add data cy on component confirmation & information](https://github.com/jabardigitalservice/super-app-cms/commit/233d5af3634513abfa67853e67f7d096c7c8bb8e)
title: feat add data cy on component confirmation & information dialog verification complaint
participants: @marsellavaleria19 @rayfajars @agunghide 
screenshot: https://s.digitalservice.id/VaeDP3

feat : add data cy on component confirmation & information dialog verification complaint

---

components/Base/TextArea/index.vue
components/Dialog/InputTextArea/index.vue
mixins/popup-aduan-masuk.js

[feat : add data-cy on dialog confirmation & information failed verification](https://github.com/jabardigitalservice/super-app-cms/commit/dfa0fec47267d577ad536e031b164ee4c6bfa503)
title: feat add data-cy on dialog confirmation & information failed verification
participants: @marsellavaleria19 @doohanas @azhargraha @rizfirman 
screenshot: https://s.digitalservice.id/2K4njG

feat : add data-cy on dialog confirmation & information failed verification

---

components/Aduan/index.vue

[fix : data-cy format show undefined](https://github.com/jabardigitalservice/super-app-cms/commit/3d06eb27275b32ef17613d54591048bf629f1462)
title: fix show data-cy format undefined
participants: @marsellavaleria19 @doohanas @Ibwedagama @rizfirman @yoslie 
screenshot: https://s.digitalservice.id/Ty9KPH

fix :  show data-cy format undefined

---

components/Aduan/Dialog/ProcessComplaint/index.vue

[fix : disable date on form process complaint](https://github.com/jabardigitalservice/super-app-cms/commit/a2a5691d76ba9d1f6c70ada46fcf7795c807acf7)
title: fix disable date on form process complaint
participants: @marsellavaleria19 @rayfajars @rizfirman 
screenshot: https://s.digitalservice.id/9dHeb3

fix : disable date on form process complaint

---

components/Aduan/Dialog/CreateIkp/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
constant/daftar-ikp.js

[fix : update label field "OPD Pemprov Penanggungjawab" to "Pemda Penanggugjawab"](https://github.com/jabardigitalservice/super-app-cms/commit/2bdbb782f4fa80341cc92230ffcac94691bd4ac0)
title: fix update label field "OPD Pemprov Penanggungjawab" to "Pemda Penanggungjawab"
participants: @marsellavaleria19 
screenshot: https://s.digitalservice.id/eDzgRa

fix : update label field "OPD Pemprov Penanggungjawab" to "Pemda Penanggungjawab"

---

components/Aduan/Detail/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue

[fix : issue show data on list page when click button back](https://github.com/jabardigitalservice/super-app-cms/commit/b759f1758851e0b8def2a4b4193774dd74cd82fa)
[fix : add function reset when condition valid on form process complaint](https://github.com/jabardigitalservice/super-app-cms/commit/fce130ff286fb1ba817fe6e3c6f881f70438d418)
title: Fix show data on list page when click button back and refresh on form process complaint
participants: @marsellavaleria19 @sheilaazhara @rizfirman 
screenshot: https://s.digitalservice.id/D2Rr1Z

Fix : show data on list page when click button back and refresh on form process complaint

---

components/Aduan/Detail/index.vue
components/Aduan/Dialog/ViewDocument/index.vue
components/Aduan/index.vue
store/index.js

[fix : add state global for back page](https://github.com/jabardigitalservice/super-app-cms/commit/84a3e011d75a15a6ad994fae3d83c4107e410040)
[fix : remove console log & condition with state back page](https://github.com/jabardigitalservice/super-app-cms/commit/ebc018c18aed163dbde3725a1912b343db2199ac)
[fix : hide & show list image](https://github.com/jabardigitalservice/super-app-cms/commit/40d62d149743b842bd9ddc0f3e158731aebc8362)
title: Fix issue back page & show hide list image on dialog document evidence
participants: @marsellavaleria19 @doohanas @rayfajars 
screenshot: https://s.digitalservice.id/4xG12U

Fix : issue back page & show hide list image on dialog document evidence

---

components/Aduan/Dialog/ProcessComplaint/index.vue
mixins/popup-aduan-masuk.js

[feat : add data-cy dialog confirmation diverted to hotline jabar](https://github.com/jabardigitalservice/super-app-cms/commit/741b8eed0363ea3a58d8158dda7058be4b6ba299)
[fix : reset field when change field coverage of affair on form proces…](https://github.com/jabardigitalservice/super-app-cms/commit/7c7e10d75f82958a28929f8522e2636eef40b89e)
title: Fix add data cy on dialog diverted to hotline jabar & reset some field on form process complaint
participants: @marsellavaleria19 @rayfajars 
screenshot: https://s.digitalservice.id/pufGq0

Fix : add data cy on dialog diverted to hotline jabar & reset some field on form process complaint

---

components/KlaimRW/index.vue
constant/menuList.js
middleware/guardRoutes.js

[feat : show title menu & direct page first login for role team hotline](https://github.com/jabardigitalservice/super-app-cms/commit/419c3b4d23384784dcc82b1afa913a598824dd03)
[fix : remove condition undefined response data on component klaim rw](https://github.com/jabardigitalservice/super-app-cms/commit/b830c594966284ec14efd9ea5eb6dc714211d4b2)
[feat : add roles 'admin:aduan-team-1' for access menu "Daftar Aduan Hotline Jabar](https://github.com/jabardigitalservice/super-app-cms/commit/0bc9f892bf13f9063a7e47f0b5548bd48eba5b1b)
[fix : change link redirect first login](https://github.com/jabardigitalservice/super-app-cms/commit/9008f36bde404d158773a1ff46c0d632f03e0aa6)
title: Hotfix issue title menu role hotline jabar & data response klaim rw
participants: …

Hotfix : issue title menu role hotline jabar & data response klaim rw

---

components/Base/Button/index.vue
pages/login.vue

[feat : add data-cy button direct login](https://github.com/jabardigitalservice/super-app-cms/commit/0f26362402cccf90e18aa2339e4acc97433b5986)
title: feat : add data-cy on button direct login
participants: @marsellavaleria19 @doohanas @yoslie @rayfajars  
screenshot: https://s.digitalservice.id/o10mrT

feat : add data-cy on button direct login

---

middleware/guardRoutes.js

[hotfix : update link path for redirect first login](https://github.com/jabardigitalservice/super-app-cms/commit/1524c05b411ba05d275debfc0180a5f419537e6a)
title: hotfix update link path for redirect first login
participants: @marsellavaleria19 @doohanas @yoslie @rayfajars @sheilaazhara @Ibwedagama 
screenshot: https://s.digitalservice.id/Tlu5It

hotfix : update link path for redirect first login

---

middleware/guardRoutes.js

fix confilct history PR production
title:Fix history pr
participants:  @rayfajars @marsellavaleria19

Fix history pr production aduan

---

docs/pull_request_template.md

- changes name project doc pr request from JSA to Sapawarga
title: chore changes name project pr request doc
participants: @rayfajars @doohanas @agunghide @Ibwedagama

chore: changes name project pr request doc

---

constant/aduan-masuk.js

[[Aduan Warga] CMS - Hide kolom tanggal verifikasi SPAN pada menu Dialihkan ke SPAN](https://app.clickup.com/t/9003239225/CES-15391)
[fix(diverted to span) : hide column diverted to span at](https://github.com/jabardigitalservice/super-app-cms/commit/25140f6dbcd8ef6ecbe2d5fac3c949289c4d7bb6)
title: Fix hide column date diverted to span on menu diverted to span
participants: @marsellavaleria19 @rayfajars @azhargraha @agunghide @Ibwedagama 
screenshot: https://s.digitalservice.id/uoZKus

Fix : hide column date diverted to span on menu diverted to span

---

docs/pull_request_template.md

add screenshot pr template
title: chore: add screen shot tempalte pr
participants: @rayfajars @doohanas @agunghide @sheilaazhara @marsellavaleria19 @Ibwedagama 
screenshot: https://s.digitalservice.id/qF64gZ

chore: add screenshot tempalte pr

---

components/Aduan/Detail/Table/EvidenceFollowup/index.vue
components/Aduan/Detail/index.vue

[[Aduan Warga] CMS staging- Fixing Bukti evidence tidak muncul](https://app.clickup.com/t/9003239225/CES-15399)
[fix(hotline-jabar): fixing issue not show evidence document & photo](https://github.com/jabardigitalservice/super-app-cms/commit/b4096a62e2bf5b25220e12fb436d038f9ed53c5b)
title: Fix issue not show evidence document & photo on feature hotline jabar
participants: @marsellavaleria19 @rayfajars @azhargraha @agunghide @Ibwedagama 
screenshot: https://s.digitalservice.id/FrxcZ0

Fix : issue not show evidence document & photo on feature hotline jabar

---

assets/css/style.css
components/Aduan/Dialog/AddComplaint/Form/LocationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue

[[Aduan Warga] CMS - Menambahkan fungsi Search](https://app.clickup.com/t/9003239225/CES-15384)
- change component select to base component select search
- change field select using search input
- add style form select search on css global
title: Add search input option dropdown on form process & form add complaint 
participants: @marsellavaleria19 @doohanas @yoslie @rayfajars @azhargraha @agunghide @sheilaazhara 
screenshot: https://s.digitalservice.id/b6kY6g

Improve : add search input option dropdown on form process & form add complaint 

---

assets/css/style.css
components/Aduan/Dialog/AddComplaint/Form/LocationComplaint/index.vue
components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/AddComplaint/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue

[[Aduan Warga] Fixing issue fungsi search di staging](url)
[fix : issue input search not show on staging](https://github.com/jabardigitalservice/super-app-cms/commit/73124b37d8ee117398cdc43506f7641629ed5a46)
title: fix issue input search not show on staging
participants: @marsellavaleria19 @rayfajars @agunghide 
screenshot: https://s.digitalservice.id/tsyo1Y

fix : issue input search not show on staging

---

components/Aduan/DaftarIKP/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue

[[Aduan Warga] CMS - BE - Menampilkan  data ID IKP production](https://app.clickup.com/t/9003239225/CES-15395)
- change default date show data instruction on tab instruction & followup instruction
- filter data by status not_yet_coordination'  
title: Fix show data instruction
participants: @marsellavaleria19 @doohanas @rayfajars @agunghide @sheilaazhara 
screenshot: https://s.digitalservice.id/23KoAZ

Fix : show data instruction

---

components/Aduan/Detail/Table/Complaint/index.vue

[[Aduan Warga] CMS - Hapus Field Jenis Media Sosial dan Link Akun Media Sosial ](https://app.clickup.com/t/9003239225/CES-15795)
[fix : remove field social media on page detail complaint](https://github.com/jabardigitalservice/super-app-cms/commit/c6a45af64e6994f7c1ae4440bb0661be3ca0b8ae)
title: fix remove field social media on page detail complaint
participants: @marsellavaleria19 @ekadhirapratama @doohanas @rayfajars @agunghide @sheilaazhara @Ibwedagama 
screenshot: https://s.digitalservice.id/7uSKHS

fix : remove field social media on page detail complaint

---

components/Aduan/Detail/Table/Complaint/index.vue

[[Aduan Warga] CMS - Menambahkan field Jenis Aduan di section Informasi Pelapor](https://app.clickup.com/t/9003239225/CES-15796)
[feat : add field complaint type on page detail complaint](https://github.com/jabardigitalservice/super-app-cms/commit/3de6127fadefc2b904be67e56c25efd73b0e7260)
title: feat add field complaint type on page detail complaint
participants: @marsellavaleria19 @rayfajars @agunghide @sheilaazhara @Ibwedagama 
screenshot: https://s.digitalservice.id/zbhrNx

feat : add field complaint type on page detail complaint

---

components/Aduan/Detail/Table/Complaint/index.vue
constant/aduan-masuk.js

- fix issue field complaint type not show
- feat add detail field complaint type on constant file
title: Fix : issue field complaint type not show on staging
participants: @marsellavaleria19 @rayfajars @yoslie @doohanas 
screenshot: https://s.digitalservice.id/a5bFkz

Fix : issue field complaint type not show on staging

---

components/Aduan/index.vue
mixins/popup-aduan-masuk.js

[[Aduan Warga] Ubah warna backdrop ketika pop up muncul](https://app.clickup.com/t/9003239225/CES-29415)
[fix : issue show popup form process complaint](https://github.com/jabardigitalservice/super-app-cms/commit/dd16679d9e0516b65da71e91b6652e7bb986669d)
[fix : issue condition close popup when submit on popup verification complaint](https://github.com/jabardigitalservice/super-app-cms/commit/3204e2e50f5d2f220d537a1f1ec61a719d45c660)
title: Fix issue show popup on feature complaint
participants: @marsellavaleria19 @sheilaazhara @rayfajars @aminnur-ikhsan 
screenshot: https://s.digitalservice.id/1CnDY1

Fix : issue show popup on feature complaint

---

components/Aduan/Dialog/AddComplaint/index.vue
components/Aduan/Dialog/EvidenceFollowupHotline/index.vue
components/Aduan/Dialog/FollowupComplaint/index.vue
components/Aduan/Dialog/FollowupHotlineJabar/index.vue
components/Aduan/Dialog/ProcessComplaint/index.vue
components/Aduan/index.vue
components/Dialog/InputTextArea/index.vue
mixins/popup-aduan-masuk.js
store/add-complaint.js
store/create-ikp.js

[[Aduan Warga] Logic button "Coba Lagi"](https://app.clickup.com/t/9003239225/CES-29416)
- change color button "Coba Lagi"
- change function for show popup create instruction
- change url api for testing 
- change url api & add condition on function retry submit for some feature on mixins popup aduan masuk
title:  Fix issue retry button not back to form
participants: @marsellavaleria19 @sheilaazhara @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/yPS2c4

Fix : issue retry button not back to form

---

components/Aduan/Dialog/ProcessComplaint/index.vue
mixins/popup-aduan-masuk.js

[[Aduan Warga] CMS - warna backdrop hitam di form Ubah Kewenangan](https://app.clickup.com/t/9003239225/CES-29742)
[refactor: add condition field select option null](https://github.com/jabardigitalservice/super-app-cms/commit/f5c8d8edeac7baa06a2d34ab89732f09af02f3da)
[fix : issue backdrop form change authority](https://github.com/jabardigitalservice/super-app-cms/commit/93ac46d5d195f0b1f978ebed38e47a49d94b56a2)
title: Fix issue backdrop on form change authority
participants: @marsellavaleria19 @Ibwedagama @yoslie 
screenshot: https://s.digitalservice.id/BbEf38

Fix : issue backdrop on form change authority

---

components/Aduan/Dialog/ProcessComplaint/index.vue

[[Aduan Warga] Menambah limit karakter di Keterangan Status Aduan](https://app.clickup.com/t/9003239225/CES-29745)
[fix(process complaint) : change limit character of status description complaint](https://github.com/jabardigitalservice/super-app-cms/commit/4c49e60fbecb96cd4f8ae97e434ea047fa6b4693)
title: fix change limit character of status description complaint on form process complaint
participants: @marsellavaleria19 @agunghide 
screenshot: https://s.digitalservice.id/2hKH3L

fix : change limit character of status description complaint on form process complaint

---

components/Aduan/Dialog/ProcessComplaint/index.vue

[fix (form process complaint) : change placeholder wording on field proposed instruction](https://github.com/jabardigitalservice/super-app-cms/commit/6b9ed70aaddcf8b839baa7086e0d050df37b411a)
title: Fix change placeholder wording on field proposed instruction form process complaint
participants: @marsellavaleria19 @sheilaazhara @rayfajars @yoslie @doohanas @ekadhirapratama 
screenshot: https://s.digitalservice.id/KUg6ah

Fix : change placeholder wording on field proposed instruction form process complaint

---

components/Aduan/Dialog/AddIdSpan/index.vue
mixins/popup-aduan-masuk.js
store/id-span.js
store/popup-complaint.js

[fix(add id span) : issue error when submit id span](https://github.com/jabardigitalservice/super-app-cms/commit/a4f3df2e9a0575270ae2378512aabc497faed5ed)
title: fix : issue error when submit id span
participants: @marsellavaleria19 @DzikriAzzakah @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/vGYJd1

fix : issue error when submit id span

---

components/Aduan/DialogViewImage/index.vue

[[Aduan Warga] resize preview foto bukti aduan](https://app.clickup.com/t/9003239225/CES-29783)
[fix : issue resize photo complaint](https://github.com/jabardigitalservice/super-app-cms/commit/8d11e78ccde970a14ea1d9b198b8ced8bde26211)
title: Fix issue rezise photo complaint
participants: @marsellavaleria19 @agunghide @azhargraha @rayfajars 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzQxNjc0MzUxNDgxLTAuOTEzNTQ4OTQxMzM3MjM5My53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9Q1F5Um1QRTBrdkpqa0h0ZyUyRjIwMjUwMzExJTJGYXNpYS1zb3V0aGVhc3QyLWElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDA2MjU1MVomWC1BbXotRXhwaXJlcz02MDQ4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0Jlgt …

Fix : issue rezise photo complaint

---

components/Aduan/Dialog/AddComplaint/Form/OthersComplaint/index.vue
components/Aduan/Dialog/AddComplaint/index.vue

[fix : issue popup error show when data span success submit](https://github.com/jabardigitalservice/super-app-cms/commit/ded3fdb3984bb1d95234c05e7fa787f72cdc52f1)
[fix(add complaint) : issue payload other category & sub category empty request to api](https://github.com/jabardigitalservice/super-app-cms/commit/d5a10def288080fadbafd04c3016ba7be532ce54)
title: Fix issue error submit with other category sub category on form add complaint from span
participants: @marsellavaleria19 @agunghide @rayfajars @yoslie 
screenshot: https://s.digitalservice.id/ZKvQmk

Fix : issue error submit with other category sub category on form add complaint from span

---

components/Aduan/index.vue

[Issue data aduan dari pemprov muncul di menu "Dialihkan SP4N Lapor" ](https://app.clickup.com/t/9003239225/CES-31034)
[feat:set filter status and back page to false](https://github.com/jabardigitalservice/super-app-cms/commit/792a657d1a7730cb6639516ffc1b048a009951e5)
title:  issue complaint for government show in menu diverted to span
participants: @marsellavaleria19 @sheilaazhara @agunghide @faisal-t @azhargraha 
screenshot: https://s.digitalservice.id/HunYEv

fix : issue complaint for government show in menu diverted to span

---

mixins/popup-aduan-masuk.js

[fix : button cancel not sho in information dialog error](https://github.com/jabardigitalservice/super-app-cms/commit/a9c1866d6e8b4d731852e53bfd84e187b83838ad)
title:  fix button cancel not sho in information dialog complaint error 
participants: @marsellavaleria19 @DzikriAzzakah @rayfajars 
screenshot: https://s.digitalservice.id/r7IwKK

fix : button cancel not show in information dialog complaint error 

---

components/Aduan/Detail/index.vue
constant/aduan-masuk.js
pages/aduan/instruksi-kewenangan-non-pemprov/detail/_id/index.vue

[[Aduan] Menambahkan button "Buat Instruksi" di halaman detail aduan menu "Instruksi Kewenangan Non Pemprov"](https://app.clickup.com/t/9003239225/CES-31291)
[feat(non government authority instruction) :  add button create instruction on page detail complaint](https://github.com/jabardigitalservice/super-app-cms/commit/18a02e07b6fa02f2fa9d39c4bac42d661d17a7f7)
title: feat add button create instruction on page detail complaint
participants: @marsellavaleria19 @sheilaazhara @rayfajars 
screenshot: https://s.digitalservice.id/msAF0V

feat(non government authority instruction) : add button create instruction on page detail complaint

---

components/Aduan/Detail/index.vue
components/Aduan/Dialog/AddIdSpan/index.vue

[[Aduan]- Issue input maksimal karakter ID SP4N Lapor](https://app.clickup.com/t/9003239225/CES-31371)
[fix(add id span) : change max character on field id span](https://github.com/jabardigitalservice/super-app-cms/commit/fceaebb8ffb3aabe254ef5d92637d795221b5940)
[fix(diverted to span) : condition complaint status when no id span](https://github.com/jabardigitalservice/super-app-cms/commit/09c8b3f603bb38f6a5c8f7d27982f5dc3f7c3263)
title: Fix : issue max character id span on feature diverted to span
participants: @marsellavaleria19 @yoslie 
screenshot: https://s.digitalservice.id/VVuJkn

Fix : issue max character id span on feature diverted to span

---

components/Aduan/Detail/index.vue

[refactor(diverted to span) : add condition type aduan page on detail ](https://github.com/jabardigitalservice/super-app-cms/commit/8815b06d895ba5c28017ac4235b8f16a6ecafd73)
title: Refactor add condition type aduan props for feature diverted to span
participants: @marsellavaleria19 @azhargraha @rayfajars 
screenshot: https://s.digitalservice.id/kjsp0j

Refactor : add condition type aduan props for feature diverted to span

---

components/Aduan/Dialog/FollowupComplaint/index.vue

[Menambahkan alert untuk aduan yang melebihi tanggal deadline](https://app.clickup.com/t/9003239225/CES-31541)
[feat(form followup complaint) : add alert for the complaint deadline date has passed](https://github.com/jabardigitalservice/super-app-cms/commit/d7650c29cbf0ecb2eb951d5c9b24a8cc235244ed)
title: feat add alert for the complaint deadline date has passed on form followup complaint
participants: @marsellavaleria19 @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/Wpvxgd

feat(form followup complaint) : add alert for the complaint deadline date has passed

---

constant/menuList.js

- add unleash klaim rw and message notif
title: feat add unleash klaim rw
participants: @rayfajars @sheilaazhara 
screenshot: https://s.digitalservice.id/Vw43GU

feat: add unleash klaim rw

---

components/Aduan/Dialog/CreateIkp/index.vue

[Enabled field tanggal deadline pada form buat instruksi baru](https://app.clickup.com/t/9003239225/CES-31721)
[fix : enabled field deadline date on form create instruction](https://github.com/jabardigitalservice/super-app-cms/commit/614dcc11e4a9e94ff3de0dd4b5461cb32b0e4d47)
Before
After
title: fix enabled field deadline date on form create instruction
participants: @marsellavaleria19 @sheilaazhara @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/fkI9ZV

fix : enabled field deadline date on form create instruction

---

components/Aduan/DaftarIKP/index.vue
mixins/popup-aduan-masuk.js
pages/aduan/instruksi-kewenangan-pemprov/detail-ikp/_id/index.vue

[Memunculkan Popup Ubah Instruksi pada Halaman Detail Pemprov](https://app.clickup.com/t/9003239225/CES-31808)
[feat : add component & function for update instruction](https://github.com/jabardigitalservice/super-app-cms/commit/6eeb39d80c5c7b2dab202645e88a4d5d6361cce1)
[refactor : parse indicatior value to integer.](https://github.com/jabardigitalservice/super-app-cms/commit/19ab356dc3635f98d0160efe8582a4ca5aa418b1)
https://github.com/user-attachments/assets/300558e7-010b-45d6-9c7c-e74e5cca261c
title: Feat add form update instruction on page detail government authority instruction
participants: @marsellavaleria19 @sheilaazhara @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/fHhvWg

Feat : add form update instruction on page detail government authority instruction

---

components/Base/Dialog/Description/index.vue
components/Dialog/ConfirmationBasic/index.vue
components/KlaimRW/index.vue
constant/klaim-rw.js
mixins/klaim-rw.js

[Nama dan email user tidak tampil di popup konfirmasi tolak klaim RW](https://app.clickup.com/t/9003239225/CES-31945)
[fix : issue email & username not show at popup confirmation](https://github.com/jabardigitalservice/super-app-cms/commit/0e98d8fdc56d0f4bd42247f049f56508bb679697)
title: fix issue email & username not show at popup confirmation klaim RW
participants: @marsellavaleria19 @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/IbS88e

fix : issue email & username not show at popup confirmation klaim RW

---

components/KlaimRW/KlaimRwDetail/index.vue
mixins/klaim-rw.js

[[Klaim RW] Issue tidak bisa menolak data akun klaim RW pada halaman detail](https://app.clickup.com/t/9003239225/CES-31905)
[fix : issue error reject klaim rw on page detail](https://github.com/jabardigitalservice/super-app-cms/commit/5d1fa2a2c613c67773db22bc980badef8218de31)
title: fix issue error reject klaim rw on page detail 
participants: @marsellavaleria19 @sheilaazhara @agunghide @yoslie 
screenshot: https://s.digitalservice.id/qpHDso

fix : issue error reject account klaim rw on page detail  

---

mixins/popup-aduan-masuk.js
store/create-ikp.js

[Memperbaiki issue cache buat ikp](https://app.clickup.com/t/9003239225/CES-32011)
[fix : issue cache create instruction](https://github.com/jabardigitalservice/super-app-cms/commit/9008eb4b136ec07653f3a393a5941c2373c88ac5)
title: fix issue cache create instruction
participants: @marsellavaleria19 @sheilaazhara @agunghide @rayfajars 
screenshot: https://s.digitalservice.id/cH3OgM

fix : issue cache create instruction
